Yoast/wpseo-woocommerce

.jscsrc, .travis.yml, Gruntfile.js, class-product-wpseo-woocommerce.php, class-wpseo-option-woo.php, codesniffer.xml, grunt/config/addtextdomain.js, grunt/config/aliases.yaml, grunt/config/checktextdomain.js, grunt/config/glotpress_download.js, grunt/config/jscs.js, grunt/config/jshint.js, grunt/config/jsonlint.js, grunt/config/jsvalidate.js, grunt/config/makepot.js, grunt/config/phpcs.js, grunt/config/phplint.js, grunt/config/watch.js, package.json, phpunit.xml, tests/bootstrap.php, tests/framework/class-wpseo-woocommerce-unit-test-case.php, tests/index.php, tests/test-class-admin-page.php, wpseo-woocommerce.php
@jdevalk or @tacoverdo please review
=> add new grunt setup and testsuite

wpseo-woocommerce.php
=> Moving the Facebook image up when this is filled [Delivers #88419006]

wpseo-woocommerce.php
=> Check if class woo commerce exists [Delivers #87198510]

class-wpseo-option-woo.php, wpseo-woocommerce.php
=> Wrapper method for validate_bool [Delivers #90991800]

wpseo-woocommerce.php
The hooks should be replaced by JS-hooks.
=> Remove deprecated hooks

class-product-wpseo-woocommerce.php
See https://github.com/Yoast/wordpress-seo-premium/pull/468
=> Use HTTP for the license manager

class-product-wpseo-woocommerce.php
For acceptance: simply test if license activation still works...
=> Make sure license calls go to the edd-sl-api endpoint.

wpseo-woocommerce.php
When the plugin is activated we should try to activate the license as well.
=> Activate license on plugin activation.

wpseo-woocommerce.php
as the Product twitter card no longer exists...
Fixes #68
=> Remove all the Twitter card functionality

composer.json, composer.lock
Fixes autoload generation failing on latest Composer versions.
=> Updated composer-php52 dependency

README.md
=> Changelog3.8

README.md
Adds changelog for 4.1
Includes missing years on the previous entries.
=> Adds changelog for 4.1

README.md
Added changelog for release 4.2
=> Added changelog for 4.2

classes/class-wpseo-option-woo.php, wpseo-woocommerce.php
* Use a filter to add opengraph images.
* Check if the default image isn't set anymore.
Fixes #71
=> Use filter to set images.

README.md
Adds changelog for 4.3
BEFORE merging, please change the base branch to the current release branch!
=> Adds changelog for 4.3

composer.json, composer.lock, wpseo-woocommerce.php
* Updates yoast-i18n to 2.0
* Make sure we don't have fatals
=> Update yoast-i18n to 2.0.1

classes/class-product-wpseo-woocommerce.php
* Changes the license lookup endpoint to my.yoast.com
=> Make sure the endpoint goes to my.yoast.com

.travis.yml, phpunit.xml, tests/bootstrap.php
Makes it possible to run the phpunit tests.
=> Fix test setup

classes/class-wpseo-option-woo.php, tests/classes/test-class-beacon-setting.php, tests/classes/test-class-wpseo-option-woo.php, tests/doubles/option-woo-double.php, tests/test-class-admin-page.php
I've added unittests to cover some of the code.
=> Add unit tests

composer.json, composer.lock, wpseo-woocommerce.php
* Upgrades Yoast Coding Standards to the latest version.
=> Upgrade YoastCS to the latest version

wpseo-woocommerce.php
* Fixes a bug where a non-existing file has been enqueued.
* Checkout `trunk` and go to the WooCommerce SEO page in the admin menu.
* A console error should be visible.
* Checkout this branch and see the error being solved.
Fixes #176
=> Stop enqueueing a non existing file.

.travis.yml
Fixes https://github.com/Yoast/wordpress-seo/issues/8415
=> Bumps PHP and WordPress versions in travis

.travis.yml
This should speed up the build on travis.
=> Remove composer version lock

classes/class-beacon-setting.php, classes/class-wpseo-option-woo.php, tests/framework/class-wpseo-woocommerce-unit-test-case.php, tests/index.php
* _N/A_
Please look at the individual commits for more details.
_N/A_
=> Clean up various superfluous code snippets

tests/framework/class-wpseo-woocommerce-unit-test-case.php, wpseo-woocommerce.php
_N/A_
Please look at the individual commits for more info.
_N/A_
=> CS/QA: various minor cs fixes

wpseo-woocommerce.php
_Security hardening_
* QA/CS compliance.
All output should be escaped, including translations.
Includes minor function layout fix which will improve the compatibility of the code with automated POT file generators.
Testing recommended, but no problems expected.
Test this by checking the label of the submenu item in the admin menu.
=> CS/XSS: always escape output [1]

classes/class-beacon-setting.php, classes/class-product-wpseo-woocommerce.php, classes/class-wpseo-option-woo.php, tests/bootstrap.php, tests/classes/test-class-beacon-setting.php, tests/classes/test-class-wpseo-option-woo.php, tests/doubles/option-woo-double.php, tests/framework/class-wpseo-woocommerce-unit-test-case.php, tests/test-class-wpseo-woocommerce.php, wpseo-woocommerce.php
_N/A_
* Documentation CS compliance.
This PR will be easiest to review by looking at each commit individually.
_N/A_
=> Documentation: various fixes

wpseo-woocommerce.php
* _N/A_
* No functional changes
* Minor documentation standards compliance fix.
* _N/A_
=> Documentation: minor doc format fix file docblock main file

tests/doubles/woocommerce-seo-double.php
=> Documentation: fix up docs for newly introduced test double

README.md, wpseo-woocommerce.php
* _Renewed compatibility with the [Plugin Dependencies](http://wordpress.org/plugins/plugin-dependencies/) plugin._
* Fixes compatibility with the [Plugin Dependencies](http://wordpress.org/plugins/plugin-dependencies/) plugin.
* Activate the Plugin Dependencies plugin
* Using the `master` branch: open the plugins page and do **not** see the dependencies correctly identified.
* Using this branch: open the plugins page and see the dependencies correctly identified.
=> Update `Depends` header

.travis.yml
=> Apply folds and multiline conditionals

wpseo-woocommerce.php
* Updated Yoast SEO product name in plugin description
*
*
Fixes #
=> update product name

wpseo-woocommerce.php
* Specifically declared WooCommerce version support.
Fixes #224
=> Add WC plugin headers

.travis.yml
* N/A
* Replacing the regex with a better one and fixing some other things I discussed with @atimmer 
* check if this fixes the build: https://travis-ci.org/Yoast/wpseo-woocommerce/jobs/421474788
=> Updated regex and added a env variable.

wpseo-woocommerce.php
* N/A - License manager related code is removed.
*
* The updating routine should be done by by the newly added addon manager.
Parent https://github.com/Yoast/wordpress-seo/issues/12150
=> Remove all license manager related code

tests/woocommerce-seo-test.php, wpseo-woocommerce.php
=> Require Yoast SEO 10.2

classes/woocommerce-schema.php
Found a bunch of things I needed to fix to make the Schema output for Woo better.
Specifically:
* Removed `mainEntityOfPage` from `Product` and moved it to `mainEntity` on`WebPage`.
* Remove single `Review` from Woo's `Product` output.
* Properly link `Review`s from Woo's separate output to the `Product`.
* Properly link the `seller` attribute to `Organization`.
=> WooCommerce schema improvements

classes/woocommerce-schema.php
* [not-userfacing] Fixes warning on product pages when a review was added.
* Create a new product. Make sure it has no offers (sale).
* Publish it.
* Add a review.
* Make sure there is no warning as shown in #355.
Fixes #355
=> Fixes warning on product pages with review

README.md
* N/A
* Bump tested up to version to 5.2
* N/A
Fixes #
=> Bump Tested up to version tot WP 5.2

tests/bootstrap.php
* _N/A_
Basically the same change as previously made in #371, but now for the newly introduced BrainMonkey based tests.
* Throw away the `vendor` directory and try to run the unit tests. See a fatal error.
* Switch to this branch, do the same, see a helpful error message.
=> PHPUnit bootstrap: friendly error message

phpunit-integration.xml.dist, phpunit.xml.dist
* _N/A_
* Use indentation to improve readability.
* Tabs vs spaces - consistently use tabs.
* _N/A_
=> Tidy up PHPUnit config files

README.md
* Sets the minimum required WordPress version to 5.2, and the minimum PHP version to 5.6.20.
* N/A
* N/A
Fixes #
=> Set tested up to to 5.3, minimum wp to 5.2 and PHP to 5.6.20

classes/woocommerce-schema.php, tests/classes/schema-test.php
* Schema: add `@id` attribute to every individual review.
* Schema: add `name` attribute to every individual review. 
* Create a product with some reviews, see the output has the added attributes.
Fixes #412
=> Enhance Schema review output

classes/woocommerce-schema.php, tests/classes/schema-test.php
* When Organization isn't set, don't use it in our Schema output.
* See #399
Fixes #399
=> When Organization isn't set, don't use it in our Schema output.

classes/option-woo.php
* _N/A_
Minor code simplification.
* _N/A_
=> QA: remove unnecessary `else` control structure

integration-tests/bootstrap.php, wpseo-woocommerce.php
* _N/A_
Minor code simplification which is possible now PHP 5.6 is the minimum version.
* _N/A_
=> Modernize: use `__DIR__` instead of `dirname( __FILE__ )`

classes/woocommerce-seo.php
* _N/A_
Lower memory usage by not assigning to a variable when the only thing being done with the variable is returning it.
* _N/A_
=> QA: remove useless variable

tests/classes/woocommerce-dependencies-test.php
* _N/A_
Don't import classes if they're not being used.
* _N/A_
=> QA: remove unused use statements

tests/TestCase.php
=> QA: declare static closures as static

wpseo-woocommerce.php
* N/A - Remove typehint for og image
Fixes https://github.com/Yoast/wordpress-seo/issues/14215
=> Remove type hint and add typecheck

classes/woocommerce-seo.php
* Replace Woo Breadcrumbs with Yoast SEO breadcrumbs now works with Storefront theme too.
* Use Woo + Storefront, enable breadcrumbs, enable replacing breadcrumbs, see the breadcrumbs get replaced.
Fixes #502
=> Make replace breadcrumbs work with storefront

classes/woocommerce-utils.php, classes/woocommerce-yoast-tab.php, tests/classes/schema-test.php
* CS clean up
This generally makes for a smaller diff if something changes and improves readability.
* _N/A_
=> CS: clean up after merges

tests/classes/opengraph-test.php, tests/classes/schema-test.php, tests/classes/utils-test.php, tests/classes/woocommerce-dependencies-test.php, tests/classes/woocommerce-yoast-tab-test.php
* QA: use FQN function calls in namespaced files
* _N/A_
=> QA: use FQN function calls in namespaced files

README.md, classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Set minimum wp version to 5.3
*
*
Fixes #
=> Set minimum WP version to 5.3

classes/woocommerce-opengraph.php, classes/woocommerce-schema.php, classes/woocommerce-utils.php, tests/classes/permalink-watcher-test.php
* Docs: various tweaks
* Improved documentation
* Docs: improve specificity
... of array var/param/return types.
* Docs: fix return tags
PHP has no concept of named return variables, so the name of the variable has no value in the `@return` tag.
* Docs: minor tag alignment fix
* Docs: minor tag order fix
* Docs: use FQN 
* _N/A_
=> Docs: various tweaks

classes/woocommerce-utils.php
* Code-style consistency
* Code-style consistency
* This generally makes for a smaller diff if something changes and improves readability.
* _N/A_
=> CS: boolean operator at the start of the line in multi-line conditions

tests/classes/permalink-watcher-test.php
* Code-style consistency
* Code-style consistency
Always be explicit about which classes are being used in a namespaced file, even when it's a class from within the same namespace.
* _N/A_ If the tests pass, we're good.
=> QA: add missing import `use` statements for classes

classes/presenters/woocommerce-product-price-amount-presenter.php, classes/presenters/woocommerce-product-price-currency-presenter.php, classes/presenters/woocommerce-product-retailer-item-id-presenter.php, classes/woocommerce-schema.php, tests/classes/schema-test.php, tests/classes/seo-trait.php, tests/doubles/schema-double.php, tests/mocks/schema-ids.php, tests/mocks/yoastseo.php
* Fixes #582 by using the proper new Schema image helper
* Fixes #583 by filtering out the presenter
* Fixes #586 by hard casting to `string`
* None needed.
* Used the surface everywhere for both `canonical` and `site_url`.
* See the individual bugs below for how to reproduce.
Fixes #582
Fixes #583 
Fixes #586
=> Fix several issues

tests/classes/twitter-test.php
* Code style consistency
* Code style consistency
Unused variables are unnecessary ;-)
* _N/A_
This is a test-only change and should have no effect on the functionality.
=> QA: remove unused variable

classes/woocommerce-schema.php, tests/classes/presenters/product-price-amount-presenter-test.php, tests/classes/presenters/product-price-currency-presenter-test.php, tests/mocks/schema-ids.php
* Code style consistency
* Code style consistency
Various minor whitespace fixes.
* _N/A_
=> CS: minor fixes

package.json, yarn.lock
* Upgrades plugin-grunt-tasks, gets rid of the sass dependency. Since there's no CSS in this plugin, no impact.
* See if all grunt commands work as expected.
=> Upgrade plugin grunt tasks

wpseo-woocommerce.php
*
* Set wc tested up to to 4.4.0
*
*
Fixes #
=> Set WC tested up to to 4.4

wpseo-woocommerce.php
* On September 8th Woocommerce 4.5 will be released
* Set the WC tested up to version to 4.5 in preparation for the WooCommerce release on September 8th.
*
*
Fixes #
=> Up WC tested up to to 4.5.0

wpseo-woocommerce.php
* WooCommerce is planning on releasing 4.6 on October 13.
* Bump the WooCommerce version to 4.6
*
*
Fixes #
=> Update WC tested up to to 4.6

.travis.yml
* For context, see https://github.com/Yoast/wordpress-seo/pull/16246
* Downgrades composer to 1.10.16 on Travis.
*
* Travis build should pass.
Fixes #
=> Travis: downgrade composer to `1.10.16`

wpseo-woocommerce.php
*
* Update WC tested up to version to 4.7
*
* Don't see warnings about not tested versions
*
*
Fixes #
=> Update WC tested up to 4.7

Gruntfile.js
* As plugin-grunt-tasks has been updated, the workaround for .sass files is no longer needed.
* As plugin-grunt-tasks has been updated, the workaround for .sass files is no longer needed.
*
* As this is devtooling no further testing is required
*
*
Fixes #
=> remove grunt watch sass workaround

.travis.yml
* 
* Updates the security checker to fix the build.
*
*
*
*
Fixes #
=> Replace the security checker

.travis.yml, README.md
* On March 9th, WordPress 5.7 will be released. We always support the 2 latest versions.
* Sets the WordPress tested up to version to 5.7 and minimum supported WordPress version to 5.6.
* N/A
* N/A
* N/A
* N/A
Fixes #
=> Set tested up to to WP 5.7 and minimum to 5.6

js/src/assessments/ProductDescriptionAssessment.js
*
* Adapt import from yoastseo
*
* This PR can be tested together with [this wordpress-seo PR](https://github.com/Yoast/wordpress-seo/pull/16913)
*
*
Fixes https://yoast.atlassian.net/browse/LINGO-772
=> Adapt import from yoastseo

.travis.yml, scripts/deploy_to_dist.sh
Allows deployments of other branches instead of only tagged commits.
Deploys the following branches and tagged commits on trunk
- `feature/`
- `release/`
- `hotfix/`
=> Deploy changes

.travis.yml, scripts/deploy_to_dist.sh
* Merges all changes from the monorepo and language split features
*
* Adapts import from yoastseo
*
*
*
Fixes #
=> Merge language split feature branch

classes/woocommerce-seo.php
https://github.com/Yoast/wpseo-woocommerce/issues/637
=> Update deprecated jQuery ready syntax

package.json, yarn.lock
* Update grunt-plugin-tasks to 2.1.2
*
*
*
*
Fixes #
=> Update grunt-plugin-tasks to 2.1.2

.travis.yml, README.md, wpseo-woocommerce.php
* On July 13th, WC 5.5 will be released.
* On July 20th, WP 5.8 will be released.
* Set tested up to version to WP 5.8 and WC tested up to version to 5.5.
*
*
*
*
Fixes #
=> Set WP tested up to to 5.8 and WC tested up to to 5.5

.adr-dir, docs/project-decisions/0001-record-architecture-decisions.md
*
* Adds Architecture Decision Records to document project decisions.
*
*
*
*
Fixes #
=> AR-238 Record architecture decisions

wpseo-woocommerce.php
* Fix shortlinks.
* None needed.
* See that plugin links have changed.
Fixes IM-1328
=> Fix shortlinks

yarn.lock
* Bump plugin-grunt-tasks to 2.2.1 This fixes a changelog issue during hotfix creation
* Bump plugin-grunt-tasks to 2.2.1 This fixes a changelog issue during hotfix creation
*
*
*
*
Fixes #
=> Bump plugin grunt tasks 2.2.1

classes/woocommerce-schema.php, tests/classes/schema-test.php
* Fixes a bug where an empty product identifier value could be output.
* Set an empty value for a product identifier like ISBN or GTIN and see that it's not output.
Fixes #IM-1612
=> Prevent outputting empty product identifiers

.travis.yml, README.md, wpseo-woocommerce.php
* WP 5.9 will be released on Jan 25
* WC 6.1 has been released
* Sets the WordPress tested up to version to 5.9.
* Sets the WooCommerce tested up to version to 6.1.
*
*
*
*
Fixes #
=> Set tested up to WC to 6.1 and WP to 5.9

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Bumps the minimum required Free version to 18.0.
*
*
*
*
Fixes #
=> Bump minimum required Free version to 18.0

.github/workflows/deploy.yml, .github/workflows/js.yml
* Update CI
* Update CI
The `setup-node` action has released a new major.
This upgrades the JS and the deploy workflow to use this new action runner.
Ref: https://github.com/actions/setup-node/releases/tag/v3.0.0
* _N/A_ If the build passes (and the deploy after the merge succeeds), we're good.
=> GH Actions: update setup-node action runner

classes/woocommerce-schema.php, tests/classes/schema-test.php
* Improve the Schema on checkout pages by removing the default `ReadAction` we used to add there.
* Improve the Schema on product pages by replacing the default `ReadAction` with a `BuyAction`. 
* See that the schema is changed as described.
Fixes PRODUCT-261
=> Improve schema on product and checkout pages

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimal required version for Yoast SEO to 18.6.
*
*
*
*
Fixes #
=> Bump version to 18.6

tests/mocks/schema-ids.php
* Update test mock to reflect the new ids that were introduced in https://github.com/Yoast/wordpress-seo/pull/18331
* Updates schema ids in test mock 
*
* No need for tests, only test file is touched
* None
Fixes #
=> Update logo hashes with changes from Free

.github/workflows/deploy.yml
*
* fix composer not updating issue with during deploy to yoast-dist
*
*
*
*
Fixes #
=> Fix composer dist

README.md
* We need to have changelog for the two latest versions to avoid breaking the automatic generation
* Adds the changelog for 14.6 to fix automatic generation.
*
* NA let's check everything works at the next changelog generation
*
*
Fixes [DUPP-427]
[DUPP-427]: https://yoast.atlassian.net/browse/DUPP-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add changelog for 14.6 to fix automatic generation

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum required Yoast SEO version to 19.1.
*
*
*
*
=> Bump minimum required free version

classes/woocommerce-schema.php, composer.lock
* Removes the `datePublished` and `dateModified` attributes on the `ItemPage` Schema markup for a Product.
* Install WooCommerce and WooCommerce SEO (without this)
* Publish a Product
* See that `datePublish` and `dateModified` are in the `ItemPage` schema.
* install this patch
* See that `datePublish` and `dateModified` are not in the `ItemPage` schema anymore
Fixes [DUPP-576]
[DUPP-576]: https://yoast.atlassian.net/browse/DUPP-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't output dates on ItemPage

classes/woocommerce-schema.php, tests/classes/schema-test.php, tests/mocks/schema-ids.php
* We should adapt the code to the changes from https://github.com/Yoast/wordpress-seo/pull/18558
* Updates the Schema manipulation to follow the new best-practice for the `@id` of the `WebPage` piece introduced by Yoast SEO 19.3.
*
* Install with current Free `trunk`
* create a product, add price, publish it
* check the Schema: the `Product` should have `mainEntityOfPage` set to the `@id` of the `WebPage`, which should be the canonical URL wihout any `#webpage` suffix.
*
*
Fixes [DUPP-590]
[DUPP-590]: …
=> Update Schema to follow the new best-practice for the @id of the WebPage piece

js/src/initializers/product-assessor.js
*
* Improves the readability analysis for English by adding a word complexity assessment for Product pages.
*
* Test together with [this PR](https://github.com/Yoast/wordpress-seo/pull/18592) and follow the testing instruction there.
*
*
Fixes https://yoast.atlassian.net/browse/PC-33
=> PC-33 Add word complexity assessment for English

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum required Yoast SEO version to 19.3.
*
*
*
*
Fixes #
=> Bump minimum required Free version to 19.3

.github/workflows/integrationtest.yml, README.md, classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum supported WordPress version to 5.9.
*
*
*
*
Fixes [PC-340]
[PC-340]: https://yoast.atlassian.net/browse/PC-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set minimum WP version to 5.9

composer.json, composer.lock
*
* Makes WooCommerce SEO compatible with the latest version of Yoast SEO.
*
* Smoke test the instructions specified in the following PRs and confirm that they still work as expected:
* https://github.com/Yoast/wordpress-seo/pull/18689
* https://github.com/Yoast/wordpress-seo/pull/18674
* https://github.com/Yoast/wordpress-seo/pull/18684
* https://github.com/Yoast/wordpress-seo/pull/18678
* https://github.com/Yoast/wordpress-seo/pull/18683
* https://github.com/Yoast/wordpress-seo/pull/18673
*
*
Fixes #
=> require Free version in the release/19.5 branch

.github/workflows/integrationtest.yml, README.md, classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum supported WordPress version to 5.9.
*
*
*
*
Fixes #
=> Bumps minimum WP version to 5.9

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum supported Yoast SEO version to 19.5.
*
*
*
*
Fixes #
=> bumps Yoast SEO to 19.5

js/src/yoastseo-woo-identifiers.js, js/src/yoastseo-woo-replacevars.js
*
* Fixes typo when retrieving element names in `yoastseo-woo-identifiers.js`
*
* Test together with https://github.com/Yoast/wordpress-seo/pull/18782
*
*
Fixes #
=> fix typos in element names

js/src/yoastseo-woo-identifiers.js
*
* Sends over the price of a simple product for the product identifier and SKU assessments.
*
* Test this PR together with https://github.com/Yoast/wordpress-seo/pull/18823 by following the test instructions of the other PR.
*
*
Fixes #
=> PC-385 - Listen for price changes of simple products and send that over to the analysis.

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum required version of Yoast SEO to 19.6.
*
*
*
*
Fixes #
=> Bump minimim required version to 19.6

README.md, classes/woocommerce-schema.php, classes/woocommerce-seo.php, classes/woocommerce-yoast-ids.php, classes/woocommerce-yoast-tab.php, js/src/yoastseo-woo-replacevars.js, tests/classes/schema-test.php
Reverts Yoast/wpseo-woocommerce#813
=> Revert "Add support for ASIN product identifier."

js/src/initializers/product-assessor.js
*
* Adds shortlinks for Title assessment.
*
* Test together with[ this PR](https://github.com/Yoast/wordpress-seo/pull/18753)
*
*
Fixes #
=> PC-191 Add shortlinks for Title assessment

js/src/yoastseo-woo-identifiers.js
*
* Does not send product price data to the analysis anymore, since the product identifiers and SKU assessment results should not depend on price.
*
* Follow the test instructions from the accompanying Free PR: https://github.com/Yoast/wordpress-seo/pull/18904
*
*
Fixes #https://yoast.atlassian.net/jira/software/c/projects/PC/boards/138?modal=detail&selectedIssue=PC-500
=> Make product identifiers and SKU assessments independent of price

js/src/yoastseo-woo-identifiers.js
*
* Checks whether we can retrieve SKU, and adds the information to the custom data that's used for the SKU assessment. Also sets the `sku` variable to an empty string when it cannot be retrieved in order to prevent errors in the plugin.
*
* Follow the instructions in the accompanying Free PR: https://github.com/Yoast/wordpress-seo/pull/18905 
*
*
Fixes https://yoast.atlassian.net/browse/PC-501
=> Check whether we can retrieve SKU and add the information to custom data

js/src/yoastseo-woo-identifiers.js
*
* Checks whether variant SKUs can be detected and adds that information to the custom data to be used in the SKU assessment.
*
* Follow the test instructions in the accompanying Free PR https://github.com/Yoast/wordpress-seo/pull/18908
*
*
Fixes #https://yoast.atlassian.net/jira/software/c/projects/PC/boards/138?modal=detail&selectedIssue=PC-504
=> Check whether variant SKUs can be detected

js/src/yoastseo-woo-identifiers.js
*
* Fixes an unreleased bug where the SKU and product identifiers assessments results would give a green bullet when only spaces are entered in the relevant field.
* It was decided to trim spaces and whitespaces from the SKUs and product identifiers
* Acivate Yoast SEO Free, Woocommerce, and Yoast SEO for Woocommerce
_Spaces in an empty field_
* Create a new product
* Confirm that the feedback for SKU gives an orange bullet and says: `Your product is missing a SKU. [Include this if you can, as it will help search engines to better understand your content.`
* Add spaces to the SKU field (`Inventory`  > `SKU`)
* Confirm that feedback for SKU does not change
* Confirm that …
=> PC 510 Remove feedback with a green bullet for spaces in SKU and product identifiers

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum required Yoast SEO version to 19.7.
*
*
*
*
Fixes #
=> Set minimum Free version to 19.7

.github/workflows/cs.yml, .github/workflows/integrationtest.yml, .github/workflows/js.yml, .github/workflows/lint.yml, .github/workflows/unittest.yml
*
* Prepares the code for a rename of the master branch to main.
*
*
*
*
Fixes #
=> Prepare renaming master to main

.github/workflows/deploy.yml
*
* Set yoast-dist deploy branch from master to main.
*
*
*
*
Fixes #
=> Set yoast-dist master to main

README.md
* Sets the WordPress tested up to version to 6.1.
* Sets the WordPress tested up to version to 6.1.
*
* NA
*
*
Fixes [PC-897]
[PC-897]: https://yoast.atlassian.net/browse/PC-897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PC-897 Set tested up to WP 6.1

README.md, config/grunt/task-config/update-changelog-to-latest.js
* Update changelog format (both in file and creation settings)
* Update changelog format (both in file and creation settings)
*
* read the new changelog, test of the grunt task was done with a Jenkins test setup.
*
*
Fixes #
=> Update changelog format (both in file and creation settings)

classes/woocommerce-seo.php, composer.json, composer.lock
* Removed the Translation "nag" from the plugin.
=> Remove unneeded dependency

README.md, package.json, yarn.lock
* Updates the `grunt-plugin-tasks` dependency to 2.4 ( this will change the initial date format to yyyy-mm-dd when creating a new RC).
* Updates the date format in README.md.
* Updates a dependency from `master` to `main`.
* Updates the `grunt-plugin-tasks` dependency to 2.4 ( this will change the initial date format to yyyy-mm-dd when creating a new RC).
* Updates the date format in README.md.
* Updates a dependency from `master` to `main`.
*
* verify the README.md
*
*
Fixes #
=> update plugin-grunt-tasks to 2.4 and update date format in readme.md

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum required Yoast SEO version to 20.2.
*
*
*
*
Fixes #
=> Bump minimum Free version to 20.2

config/webpack/webpack.config.default.js, config/webpack/webpack.config.prod.js, package.json, yarn.lock
*
* Adds bundle analyzer plugin to Webpack config and makes `lodash` external dependency.
* The BundleAnalyzerPlugin is added to the webpack config for production. This way, this plugin is only used when the production config is used and not when the development is used.
Test together with this PR: https://github.com/Yoast/wordpress-seo/pull/19921
*
*
Fixes #
=> Adds bundle analyzer plugin

wpseo-woocommerce.php
* Update the author URI to a new link.
* Updates the author uri value.
*
* Check if the `team yoast` url is the same as described in https://github.com/Yoast/wordpress-seo-premium/issues/3779
*
*
Fixes #
https://github.com/Yoast/wordpress-seo-premium/issues/3779
=> Update Author URI

README.md
* Sets the WordPress tested up to version to 6.2.
* Sets the WordPress tested up to version to 6.2.
*
*
*
*
Fixes #
=> Set the WordPress tested up to version to 6.2

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Bumps the minimum required Yoast SEO version to 20.6. 
*
*
*
*
Fixes #
=> Bump minimum required Free version to 20.6

.github/PULL_REQUEST_TEMPLATE.md
* Updating PR template to allow user to not miss log time for innovative projects, check that correct base branch is selected.
* Update PR template to not miss log time for innovative projects, check that correct base branch is selected.
*
* No testing required.
*
*
Fixes #[20402](https://github.com/Yoast/wordpress-seo/issues/20402)
=> Update templates to include list of tickets and base branch check.#20402

classes/woocommerce-seo.php
*
* Adds a line to explain the WooCommerce 7.9.0 case.
*
* Check the WooCommerce SEO settings 
* The second section should look like this:
*
*
Fixes #
=> Add new copy to let users know about the Woo 7.9.0 limitation

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
=> Bump minimum required free version to 20.12

README.md
*
* Sets the WordPress tested up to version to 6.3.
*
* NA
*
*
Fixes #
=> Sets the WordPress tested up to version to 6.3.

.github/workflows/test.yml, README.md, classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Sets the minimum supported WordPress version to 6.2.
*
* NA
*
*
Fixes #
=> Set the minimum supported WordPress version to 6.2.

phpunit-integration.xml.dist, phpunit.xml.dist
* Dev-file update
* Dev-file update
PHPUnit config: update schema reference to the minimum PHPUnit version which is currently in use.
The configuration has also been validates against the schema and where needed, updated.
* _N/A_
=> PHPUnit config: update schema reference

composer.lock
* Update YoastSEO Free (dev) dependency
* Update YoastSEO Free (dev) dependency
This fixes the following errors when running the integration tests, as the locked version of YoastSEO was from July...
Note: the error did not show in CI as the GH Actions workflow is set up to _always_ update the YoastSEO dependency before running the tests.
```
Warning: foreach() argument must be of type array|object, null given in path\to\wpseo-woocommerce\vendor\yoast\wordpress-seo\src\helpers\indexing-helper.php on line 332
Error in bootstrap script: TypeError:
Yoast\WP\SEO\Builders\Indexable_Author_Builder::__construct(): Argument #3 ($post_helper) must be of type Yoast\WP\SEO\Helpers\Post_Helper, Yoast\WP\SEO\Helpers\Options_Helper given, …
```
=> Composer: update YoastSEO Free

README.md
*
* Sets the WordPress tested up to version to 6.4.
*
*
*
*
Fixes #
=> Sets the WordPress tested up to version to 6.4

classes/woocommerce-dependencies.php, tests/classes/woocommerce-dependencies-test.php
*
* Bumps the minimum required version of Yoast SEO to 21.6.
*
*
*
*
Fixes #
=> Bump minimum required Free version to 21.6

.github/workflows/cs.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/test.yml
* QA
* QA
Update a few links in inline comments as the old URLs are no longer valid.
* _N/A_
=> GH Actions: update a few links in inline comments

wpseo-woocommerce.php
*
* Adds the header required by the Woo marketplace.
*
* N/A
*
*
Fixes #
=> Adds the header required by the Woo marketplace
