Yoast/wpseo-woocommerce

wpseo-woocommerce.php

wp_installing() is now the correct way to check if WordPress is
installing.
See https://core.trac.wordpress.org/changeset/34828

Use wp_installing

---

classes/class-product-wpseo-woocommerce.php

Changed arguments to comply with Licence Manager updates so we use an HTML ID safe string for slug needed for correct usage of the shiny updates routine.
See https://github.com/Yoast/wordpress-seo-premium/issues/274
Consideration:
We realise that using an older License Manager version might break functionality but upgrading Free or Premium will solve this (which everybody should do), so not considered a huge problem.

Fixed "update plugin" on the plugins page

---

composer.json
composer.lock
wpseo-woocommerce.php

If the home page is set to the shop page we want to exclude the 'product' link from the sitemaps.
**How to reproduce**
Prerequisites:
* WooCommerce
* Yoast SEO for WordPress
* WooCommerce for SEO
Set blog home to "shop".
Install WooCommerce dummy data (https://docs.woothemes.com/document/importing-woocommerce-dummy-data/)
Go to page 2 on the front page of the blog.
1. See if the meta fields for rel=prev and rel=next are present.
1. Go to the product-sitemap.xml and see if the "shop" / home page URL are present (it wasn't and it shouldn't)
Fixes #100

Fix rel next prev archive pages

---

classes/class-beacon-setting.php

`get_config( $page  )` will be added to the `Yoast_HelpScout_Beacon_Setting` interface to alter the help scout beacon's configuration. This allows for all instances of the help scout beacon to be set up differently. ([possible values](http://developer.helpscout.net/beacons/customization/#config-configobject-))

updated helpscout interface

---

wpseo-woocommerce.php

- [bugfix] Fixes a bug where not all Yoast SEO columns where hidden.
* -
* Follow the steps to reproduce the issue and see the issue being solved by this pull request.
Fixes #136

Remove the Yoast SEO columns if necessary.

---

wpseo-woocommerce.php

- Added fallbacks for a couple of deprecated warnings ( `get_product` => `wc_get_product`,  `WC_Product:: get_gallery_attachment_ids` => `WC_Product::get_gallery_image_ids` )
* Check if the new functions exists and call these.
* Also use some built-in methods on the product object, instead of getting the values from the object attribute directly.
* Have deprecated warnings being visible on the product page.
* Checkout this branche and see the errors being solved.

Create fallbacks for deprecated methods/functions.

---

wpseo-woocommerce.php

- Added filter to set the primary category in the permalink
* Just added the filter for WooCommerce, because it handling the custom WooCommerce permalink structure itself.
* Set two (or more) product categories, set one of these as primary category and save the product.
* The chosen one should be used in the permalink.
Fixes https://github.com/Yoast/wordpress-seo/issues/4528

Add filter for setting the primary category in the permalink.

---

.travis.yml

This is not a permanent fix, as support will be dropped in September.
See also https://core.trac.wordpress.org/changeset/41072/

Set specific dist for PHP 5.2 and PHP 5.3

---

.travis.yml
wpseo-woocommerce.php

This code cleans up some of the code in the `metadesc` function and implements a fix introduced in #90.
Changelog entry:
* Fixes a bug where the short description was cut to the hard 156-character limit.
Props to @NickIvanter for the original fix.

Don't cut hand-crafted excerpts

---

.travis.yml
wpseo-woocommerce.php

* Use the capabilities introduced in Yoast SEO 5.5 for menu registration.
* Apply patch and see the menu item being displayed when the current user has `wpseo_manage_options`

Change to new WPSEO Manage Options

---

wpseo-woocommerce.php

This prevents the gallery images to be used as page image if an image with more priority has been configured.
* Fixes a bug where the first image in the Image Gallery is used on Facebook to compliment the page when shared, instead of the configured Facebook image or Featured image.
* Add a featured image or Facebook Image to a WooCommerce Product
* Add images to the image gallery for the Product
* Without this PR the gallery images would be above the images in the `<head>` of the rendered product page
* With this PR the gallery images will be below the featured/FB image
Requires https://github.com/Yoast/wordpress-seo/pull/8267
Fixes …

Use the hook with less priority to attach images on

---

wpseo-woocommerce.php

Fixes #163 
Removes Yoast SEO, WooCommerce SEO and WooCommerce out of translations.

Remove "WooCommerce SEO" and other product names from translations

---

wpseo-woocommerce.php

Fixes a bug where there was a link to a settings page that no longer existed.
* Checkout trunk.
* Activate Yoast SEO & Yoast SEO for WooCommerce
* Go to SEO->Advanced->Breadcrumbs
* Enable breadcrumbs
* Go to SEO-> WooCommerce SEO
* See that under 'Breadcrumbs' the 'internal links settings page' url does not work.
* Checkout this PR.
* See that under 'Breadcrumbs' the link has been renamed to 'Breadcrumbs settings page' and the link now works.  
Fixes #130

Fix link to a page that has been renamed to wpseo_advanced

---

package.json
yarn.lock

* Bumps the YoastSEO version to 1.29.
* Do a `yarn install`. Check if nothing breaks.

Bump YoastSEO version to 1.29

---

.travis.yml
composer.json

_N/A_
This PR contains two tweaks to the Travis build script - each in a separate commit for easier review. Also see the commit messages for additional info:
1. On line 50 of the script, a specific PHPUnit version is pulled in via Composer for certain PHP versions. This PHPUnit version is subsequently never used.
This commit brings the command to run PHPUnit in line with this.
Alternatively, - as it looks like the build runs fine with PHPUnit 6 -, the `composer require` on line 50 could be removed.
2. Validate the `composer.json` file during the builds.
* Check the Travis build logs to see the effects.

Build: Travis tweaks

---

wpseo-woocommerce.php

* _Various (internal) methods which had been previously deprecated and had been deprecated for more than a year, have now been removed._
Removed method deprecated more than a year ago.
There are a few more deprecated methods (one or two if I remember correctly), but those are far more recent, so should remain for now.
* Things should still work as expected even when this code is removed, that's all you can check for really.

Clean up: remove methods deprecated < WooCommerce SEO 4.0

---

wpseo-woocommerce.php

* Removed backfill for `wp_installing()` as this was introduced in WordPress 4.4.
* The minimum supported WP version is now WP 4.8. The `wp_installing()` function was introduced in WP 4.4.
* The plugin should still start up & hook-in as normal. No changes should be noticeable.

Clean up: remove back-fill which is no longer needed

---

wpseo-woocommerce.php

_N/A_
* Code style compliance. Strict type comparisons should be used as a rule, with loose type comparisons being the exception.
For array functions which do loose type comparisons, setting the third `$strict` parameter to `false` can be seen as a clear indication that this is a conscious, well thought out decision by the developer.
In all other cases, `$strict` `true` should be used.
Testing recommended, though I don't expect any issues.

CS/QA: Use strict comparisons with array functions

---

wpseo-woocommerce.php

_N/A_
The `wp_strip_all_tags()` function is more comprehensive than the PHP native `strip_tags()` function.
The advantage of `wp_strip_all_tags()` over `strip_tags()` is that it does not leave the content of removed `<script>` and `<style>` tags behind.
> This differs from `strip_tags()` because it removes the contents of the `<script>` and `<style>` tags. E.g. `strip_tags( '<script>something</script>' )` will return ‘something’. `wp_strip_all_tags()` will return ”
It can also remove superfluous whitespace within the string which may be left behind after removing the tags. For this, the second parameter `$remove_breaks` needs to be passed and set to `true`.
Refs:
* https://developer.wordpress.org/reference/functions/wp_strip_all_t …

CS/QA: use `wp_strip_all_tags()`

---

wpseo-woocommerce.php

_Security hardening_
* QA/CS compliance.
All output should be escaped, including translations.
Includes minor code build-up changes.
Side-note: the version checks used in the `initialize_yoast_woocommerce_seo()` method seem a bit out of sync.... Should those be updated ?
https://github.com/Yoast/wpseo-woocommerce/blob/456cafe0273c54d97b61b30cc20f7448244467f9/wpseo-woocommerce.php#L1212-L1216
Testing recommended, but no problems expected.
Test this by triggering each error message and reviewing the output, i.e.:
* Try and use WooCommerce SEO on an old WP version
* Try and use WooCommerce SEO with a really old version of WPSEO
* Try and use WooCommerce SEO with WPSEO deactivated WPSEO.

CS/XSS: always escape output [2]

---

wpseo-woocommerce.php

_Security hardening_
* QA/CS compliance.
All output should be escaped, including translations.
Includes minor code layout changes.
Testing recommended, but no problems expected.
Test this by opening up the WooCommerce SEO settings page and verifying that all output strings are displayed properly without strange artifacts.

CS/XSS: always escape output [3]

---

composer.json
tests/doubles/woocommerce-double.php
tests/test-class-wpseo-woocommerce.php
wpseo-woocommerce.php

* Show a notice when a WordPress SEO version below 7.0 is installed.
* Show a notice when a WordPress version below 4.8 is installed.
* Have this branch and WordPress SEO active. Change in WordPress SEO the value of constant `WPSEO_VERSION` in a value below 7.0
* A notice should be shown. 
* Change the value of the constant to 7.0 or 7.1 and see the notice being gone.
* The minimal required WordPress version can be tested by adding this to the 'wpseo-woocommerce.php' file:
```php
add_action( 'admin_init', function() {
global $wp_version;
$wp_version = 4.7;
} );
```
Fixes #195 
Fixes #212

Add WordPress SEO version requirement

---

package.json
yarn.lock

* Bump YoastSEO.js to 1.30.1
* Check whether nothing breaks.

Bump YoastSEO to 1.30.1

---

package.json
yarn.lock

* Bumps YoastSEO.js to 1.31
* Check whether nothing breaks.

Bump YoastSEO.js to 1.31

---

grunt/config/makepot.js
languages/yoast-woo-seo.pot

If an artifact was build previously, this will be taken into account when re-generating the language files. Resulting in double entries which are not relevant.
* _N/A_
* Excluded the `optionally present` artifact folder from being parsed for translations.
* `grunt copy:artifact` - This generates an `artifact` folder in your local directory
* `grunt build:i18n` - This rebuilds the `pot` file
Related https://github.com/Yoast/wpseo-news/issues/406

Exclude artifact folder from pot file creation

---

.travis.yml

* _N/A_
* `remove` before `require` to always have the smallest possible install.
* Combine the two `remove` commands into one.
Ref: https://getcomposer.org/doc/03-cli.md#remove
* Travis build still works as expected.

Travis: Composer efficiency improvements

---

js/src/yoastseo-woo-replacevars.js
package.json
yarn.lock

Bump YoastSEO.js to 1.34.0
* Bumps YoastSEO.js to 1.34.0
* Fixes JS error on the product overview page.
* Check whether nothing breaks.

Bump YoastSEO.js to 1.34.0

---

wpseo-woocommerce.php

*  Adds recommended templates with replacements variables for WooCommerce pages.
* This needs: https://github.com/Yoast/wordpress-seo/pull/9963/
* Go to search appearence and see the templates works as expected for the WooCommerce pages.
Fixes https://github.com/Yoast/wordpress-seo/issues/9888

Implement filter for the recommended replacevars.

---

wpseo-woocommerce.php

* Excludes the WooCommerce core pages from the sitemap, because they will set to noindex by WooCommerce.
* Set a myaccount, cart and checkout page.
* Visit the pages sitemap and see the set pages not being visible.
Fixes https://github.com/Yoast/wordpress-seo/issues/9540

Excludes the WooCommerce core pages from the sitemap

---

tests/doubles/woocommerce-seo-double.php
tests/woocommerce-seo-test.php
wpseo-woocommerce.php

* Hides excluded catalog products from the products sitemap.
* Add a product (for example: Product A)
* View the products sitemap and verify the product being visible.
* Edit the product by excluding it from the catalog:
* Visit the sitemap and the product should be hidden.
Fixes #42

Filters excluded catalog products from the sitemap

---

package.json
yarn.lock

* N/A
* Bump YoastSEO.js to v1.36.0
*
Fixes #

Bump YoastSEO.js to v1.36.0

---

tools/grunt/config/aliases.yaml
tools/grunt/config/compress.js
tools/grunt/config/copy.js

*  N/A
* Altered some of the Grunt configuration files to be more in line with the configuration used in Free. This also resolves the issue that zips that are created, are suffixed with a random hash, resulting in faulty installs.
* Checkout this branch and ensure you've run `yarn`.
* Run `grunt artifact`.
* A zip file named `artifact.zip` should now be present in your directory. Unzip it and ensure the folder name is the same as the plugin name and does not contain a suffix.

Fixed configuration files for building artifacts

---

tests/woocommerce-seo-test.php
wpseo-woocommerce.php

* The minimal required version of Yoast SEO (Premium) has been updated to 8.1
* Install Yoast SEO 8.0 or lower
* See the message at the top of the plugins screen that Yoast SEO: WooCommerce requires the latest version of Yoast SEO to work.

Bump Yoast SEO minimal version requirement to 8.1

---

.phpcs.xml.dist
classes/option-woo.php
composer.json
composer.lock
tests/doubles/option-woo-double.php
tests/framework/woocommerce-unittestcase.php
wpseo-woocommerce.php

* _N/A_
This updates:
* PHP_CodeSniffer from v 3.3.0 => 3.3.1
* WordPressCS from v 0.14.1 => 1.0.0
* PHPCompatibility from v 8.1.0 => 8.2.0
This adds:
* PHPCompatibilityWP at v 1.0.0
The following dependencies of PHP Mess Detector, which is part of YoastCS, have also been updated:
* Symfony Filesystem from v 2.8.34 => 3.4.14
* Symfony Dependency Injection from v 2.8.34 => 3.4.14
* Symfony Config from 2..8.34 => 3.4.14
And the following sub-dependencies of these PHP Mess Detector dependencies have been added:
* Symfony Polyfill Ctype at v 1.9.0
* PSR container at v 1.0.0
Additionally, the Roave Security Advisories have been brought up to date.
* The `GlobalVariables` sniff has been renamed and moved to the `WP` category in WPCS …

PHPCS: Update to use YoastCS 1.0 / WPCS 1.0

---

wpseo-woocommerce.php

* N/A
* Fixes the following PHPCS error: 
```FILE: wpseo-woocommerce.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
1331 | ERROR | [x] Must use "self::" for local static member
|       |     reference
|       |     (Squiz.Classes.SelfMemberReference.NotUsed)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```
* Run PHPCS with and without this change. I did that using `./vendor/bin/phpcs`. See that it's …

Fix local static member reference phpcs error

---

wpseo-woocommerce.php

Fixes: https://github.com/Yoast/wpseo-woocommerce/issues/267
* Fixes a bug where the `Yoast SEO Breadcrumbs` settings page link did not go to the correct page.
* N/A
* Follow instructions in the issue
Fixes #267

Reference the correct settings page

---

composer.lock

* N/A
* Test if the help scout beacon still works on http://local.wordpress.test/wp-admin/admin.php?page=wpseo_woo

Upgrade yoast/wp-helpscout to 2.0.4 in composer.lock

---

wpseo-woocommerce.php

* Fixes a bug where the WooCommerce breadcrumbs aren't replaced by the Yoast SEO breadcrumbs.
* 
* Checkout trunk
* Under the WooCommerce SEO settings check the option`Replace WooCommerce Breadcrumbs 
`
* Go to the website and see nothing has been replaced.
* Checkout this branch and see the breadcrumbs are replaced
Fixes #150

Replace woocommerce hook

---

.phpcs.xml.dist
composer.json
composer.lock
index.php
wpseo-woocommerce.php

* Includes adding the PHPCS XSD to the custom ruleset which should now be valid as the minimum PHPCS requirement has gone up to PHPCS 3.3.2.
* Includes removing the DealerDirect Composer PHPCS plugin which now comes automatically with YoastCS.
The typical issues reported for `index.php` files are ignored by default in YoastCS.
This PR addresses some inconsistencies related to deprecated functions. It basically applies the following rules:
* Deprecated functions/methods should be at the end of the file/class.
* They should be preceded by a `/* *** DEPRECATED METHODS *** */` delimiter to clearly indicate the start of the deprecated functions.
* Deprecated functions should be ignored for the purposes of calculating code coverage via PHPUnit and therefore should each have a …

Update for YoastCS 1.1.0 / WPCS 1.2.1 / PHPCompatibility ^9.0.0

---

composer.json
composer.lock

* _N/A_
Updates the CS requirements to YoastCS 1.2.2.
No changes to the code are needed.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/1.2.0
* https://github.com/Yoast/yoastcs/releases/tag/1.2.1
* https://github.com/Yoast/yoastcs/releases/tag/1.2.2
* Either do a `composer install` and then a `vendor/bin/phpcs` òr check the Travis logs for the CS run to verify that all is well.

Composer: require YoastCS ^1.2.2

---

.phpcs.xml.dist
tests/woocommerce-seo-test.php
wpseo-woocommerce.php

* [not sure if this needs to be in the changelog] Sets the minimum required WordPress version to 5.0.
* [not sure if this needs to be in the changelog] Sets the minimum required Yoast SEO version to 10.1.
* Also sets PHPCS "minimum_supported_wp_version" to "4.8"
* Install this branch on a WP site with a version below 5.0. See a notification.
* Install this branch on an installation with a Yoast SEO version lower than 10.1. See a notification.
* Install this branch on a WP site with a version >=5.0 and Yoast SEO version >= 10.1. See no notifications.
NB. The failing tests are not related to this PR.
Fixes [Yoast/wordpress-seo#12331](https://github.com/Yoast/wordpress-seo/issues/12331) …

Bump minimal required yoastseo version to 10.1 and WordPress version to 5.0

---

wpseo-woocommerce.php

* Removed an empty method that has been deprecated since version 5.6
*
* The test should pass.
Fixes #329

Remove the deprecated function

---

wpseo-woocommerce.php

* Changes `og:brand` to `product:brand` to match the OpenGraph specifications better.
* N/A
* Enable WooCommerce SEO
* Go to SEO > WooCommerce settings
* Enable a category to use as "Brand"
* Go to a product
* Create or select a "Brand" category
* Save the product
* View the front-end page of the product
* Inspect the source and see the `product:brand` as meta entry, instead of `og:brand`
If you have a live site, you can verify with the Facebook debug tool
* https://developers.facebook.com/tools/debug/
Fixes #225

Change `og:brand` to `product:brand`

---

classes/woocommerce-schema.php
classes/wpseo-schema-woocommerce.php
wpseo-woocommerce.php

* Improves integration of Woo & Yoast's Schema output, bringing it to a whole new level.
* Removes Woo breadcrumbs Schema output.
* Changes page type on Checkout to `CheckoutPage`.
* Removes Woo breadcrumbs Schema output.
* Look at a product, grab all the source, throw it through Google's Structured Data Testing Tool.
* Look at the checkout, grab all the source, throw it through Google's Structured Data Testing Tool.
Fixes #337
Fixes #289

Make Woo Schema work with our new Schema

---

classes/woocommerce-schema.php
wpseo-woocommerce.php

* Use the WooCommerce Schema output and stitch it into the Yoast SEO Schema graph.
* Decided to block Woo from outputting its own schema, but still use its data collection features.
* Brings back `brand` and `manufacturer` attributes that I missed in the previous merge.
* Look at a product page for a product with multiple reviews, throw the output into the SDTT, and it should stitch into one graph.

Fix woo schema

---

classes/woocommerce-schema.php

* Don't output a schema graph tag when there's nothing to output in it.
* Go to a page without a product, see there's no script tag needed.

Don't output empty graphs

---

wpseo-woocommerce.php

* Disables the plugin completely when WooCommerce is not active.
* Disable `wpseo-woocommerce` entirely when WooCommerce is not active.
* See steps in #344 
Fixes #344

Don't Load when WooCommerce is not active

---

tests/classes/option-woo-test.php
tests/classes/woocommerce-beacon-setting-test.php
tests/framework/woocommerce-unittestcase.php
tests/woocommerce-seo-test.php

* _N/A_
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available have been extended hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for the Yoast WooCommerce plugin.
Refs:
* https://phpunit.de/manual/4.8/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* …

QA: use the most specific PHPUnit assertion possible

---

.phpcs.xml.dist
tests/bootstrap.php

* _N/A_
WP will load the active plugins automatically, there is no need to require YoastSEO explicitly.
Do more rigorous checking whether the environment is correctly set up for the unit tests to be run and if not, show an instructive error message.
Include disabling the security sniffs for the bootstrap file.
On `trunk`:
1. If applicable: remove the `WP_DEVELOP_DIR` environment variable from your OS or custom `phpunit.xml` file and make sure that this plugin is not in the `wp-content/plugins` directory of a WP install. Run the unit tests and see them fail with a PHP error.
2. Bring back the `WP_DEVELOP_DIR` environment variable, but set it to an invalid value. Run the unit tests …

QA: review test bootstrap file / show friendly errors

---

wpseo-woocommerce.php

* Fixes the deprecation notice of `get_woocommerce_term_meta`.
* To prevent notices in users' PHP error logs we should avoid using deprecated functions.
**Without this PR:**
1. Install `woocommerce` and `wpseo-woocommerce`
2. Create a Woocommerce product category and add an image to this category
3. Visit the front-facing product category page
4. Notice the "PHP Notice:  get_woocommerce_term_meta is <strong>deprecated</strong> since version 3.6!" message in your logs (depending on log level of PHP).
**With this PR:**
1. Perform steps 1 through 3 of previous list.
2. Notice no messages in your error log.
To debug, set a breakpoint on [line …

Fix depricated function get_woocommerce_term_meta

---

tests/classes/option-woo-test.php
tests/classes/woocommerce-beacon-setting-test.php
tests/woocommerce-seo-test.php

* _N/A_
`@covers` tags are used to indicate what class/method/function a test covers when calculating code coverage of the tests and should follow the specifications of PHPUnit.
Ref:
* https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.covers
* https://github.com/Yoast/yoastcs/issues/123
* N/A

Test documentation: fix @covers tags

---

classes/woocommerce-schema.php
wpseo-woocommerce.php

Don't initialize wpseo-woocommerce schema class when wordpress-seo schema is disabled
* Fixes a bug where the Yoast SEO WooCommerce schema was output when the `wpseo_json_ld_output` filter was set to false.
* Moved Schema initialization from `plugins_loaded` hook to `init` to make sure `functions.php` from theme's is loaded when initializing schema.
* Activate `WooCommerce` and `Yoast SEO`.
* Disable Yoast SEO schema output using `add_filter( 'wpseo_json_ld_output', '__return_false' );`. You can put that in the `functions.php` of your theme for example.
* Make sure the Yoast SEO schema is fully disabled. You can identify the Yoast SEO Woocommerce schema by the classname on the …

Disable schema when YoastSEO schema is disabled.

---

classes/woocommerce-schema.php

* Don't output image schema id if the product has no thumbnail.
* Removes image schema if it is false. This is a bug from WooCommerce.
* If a product has no defined image, fallback to WooCommerce placeholder image.
Enable `WooCommerce`, `Yoast SEO: WooCommerce` and `Yoast SEO`.
* Create a product without a product image.
* Inspect the product schema, it should not have an image node.
* Add a product image.
* Inspect the product schema, it should now have an `image` node with an `@id` property referring to the main image schema.
Fixes Yoast/bugreports#458

Don't add image id if no thumbnail is available

---

.phpcs.xml.dist
tools/grunt/config/shell.js

* _N/A_
* Revert the exclusion of the `tests` directory from the CS run.
* Use the right command in `grunt` to call PHPCS.
The Composer script was already correctly set up to allow for different minimum PHP requirements for the `tests` directory, it just needs to be used. 
@andizer Got a feeling you already know how to test this.
Fixes #408

PHPCS: Revert exclusion of test directory

---

.phpcs.xml.dist
classes/woocommerce-schema.php
composer.json
composer.lock
languages/index.php
tests/TestCase.php

*  _N/A_
Ruleset updates:
* Remove dependencies related `exclude-pattern`. These are now contained within the YoastCS ruleset as of v1.3.0.
* Remove the `languages` directory `exclude-pattern`.
The languages directory contains no PHP files, except for the empty `index.php` file, so there is no need to exclude it.
Includes very minor touch-up of the `index.php` file.
* Remove the `minimum_supported_wp_version` `config` directive. As of YoastCS 1.3.0, a default is set in the `Yoast` ruleset and should be followed by this repo.
The default in the `Yoast` ruleset at this time is `4..9`.
* Move the property setting for the `custom_test_class_whitelist` property which is used by several sniffs up to the standard inclusion.
This allows …

Composer: require YoastCS ^1.3.0 & update ruleset

---

.phpcs.xml.dist

* _N/A_
WordPressCS will demand long arrays and forbid the use of short arrays as of WPCS 2.2.0.
See: https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/
For YoastCS, however, a choice has been made to demand short arrays.
For now, while WP 4.9, and therefore PHP 5.2 still needs to be supported, this is only possible in the directories containing files with PHP 5.6+ code.
So in this interim period, we will enforce short arrays in the PHP 5.6+ code and long arrays everywhere else.
Once the minimum supported WP version has moved up to WP 5.2 / PHP 5.6, short arrays will be enforced for all code and the change-over can be done automatically using the auto-fixer included in the relevant sniff.
This PR can be …

CS: enforce consistent array format

---

tests/TestCase.php
tests/classes/schema-test.php
tests/doubles/schema-double.php

* _N/A_
* Fixes one namespace declaration containing a typo.
* Fixes spelling of `Woocommerce` in namespace declarations + use statements to the agreed upon form.
* _N/A_ these fixes are in the unit test code, not the plugin code. As long as the tests still run as expected, we're good.

CS: use the correct namespace name

---

tests/bootstrap.php

* _N/A_
`opcache_reset()` is a function, not a class.
* _N/A_

PHPUnit bootstrap: fix typo

---

tests/classes/schema-test.php

* _N/A_
Use most specific assertion for the new unit tests.
See #363 - this is basically the same change, but now for the newly added unit tests.
* If the unit tests still pass, we're good.

PHPUnit: use most specific assertion

---

tests/TestCase.php

* _N/A_
As these new tests will only be run on PHP 5.6+ in combination with PHPUnit 5.4+, use the newer namespaced PHPUnit class name.
A class alias for BC is not needed as BrainMonkey is not available on PHP < 5.6, so older PHPUnit versions do not need to be supported.
* _N/A_ If the unit tests are still being run and pass, we're good.

PHPUnit: make (new) unit tests compatible with higher PHPUnit versions

---

composer.lock

* _N/A_
Mockery `1.2.2` has issues with PHP 7.4 which have been fixed in Mockery `1.2.4` (though not mentioned in the changelog).
Ref: https://github.com/mockery/mockery/releases
* _N/A_
This is a test-dependency-only change and should have no effect on the functionality.

Update Mockery for testing on PHP 7.4

---

wpseo-woocommerce.php

* Fixes a bug where hidden products could show in XML sitemap.
* Used an unbounded query, as it only grabs the IDs, not more data, I think this won't lead to any problems.
* See reproduction steps in https://github.com/Yoast/bugreports/issues/697
Props to @Djennez for the solution.
Fixes https://github.com/Yoast/bugreports/issues/697

Remove all hidden products from XML sitemap

---

integration-tests/woocommerce-seo-test.php

* _N/A_
On PHP 7.4, these five unit tests are running into a `Trying to access array offset on value of type bool` error.
Analysis of the error shows the following:
When the MockBuilder is used to call `Yoast_WooCommerce_SEO`, the options framework is not correctly initialized.
As in a test situation, the `wpseo_woo` option will not have been saved to the database yet, this means that the `get_option()` call in the `Yoast_WooCommerce_SEO::initialize()` method will return `false` instead of the expected option defaults.
https://github.com/Yoast/wpseo-woocommerce/blob/98194c61fa09d1eed958fcf0906b71ace436faa8/wpseo-woocommerce.php#L150
When subsequently, array access is attempted on the option - as happens numerous times in the rest …

Tests: fix compatibility with PHP 7.4

---

.travis.yml
README.md
composer.json
composer.lock
integration-tests/bootstrap.php
wpseo-woocommerce.php

* _N/A_
Brief analysis of the Travis script shows me that:
* There are a number of builds _which do not do anything_.
All the tasks in `script` are set up conditionally based on environment variables.
Any build which did not have an environment variable, such as `PHPLINT`, `PHPCS` or `PHPUNIT` was basically completely useless.
* While the `PHPUNIT` task is set up to run conditionally, the _preparation of the environment_ for unit testing, i.e. downloading WordPress, cloning YoastSEO Free, setting up the database _is all done **unconditionally**_.
So, with that in mind, I have made the following changes to the Travis script - please read this carefully:
* Removing builds against PHP < 5.6.
* Changing the `WP_VERSION` environment …

Stop explicit support for PHP < 5.6 / WP < 5.2

---

classes/woocommerce-schema.php

* N/A - Makes sure the canonical is fetch the right way.
*
* Please test this against the `features/indexables-frontend` branch in Yoast SEO free
* Have WooCommerce active and add a product
* View the product and verify the canonical is in the WooCommerce schema output.
This is part of https://github.com/Yoast/wordpress-seo/issues/13832

Prepare for indexables

---

integration-tests/woocommerce-seo-test.php
wpseo-woocommerce.php

* Sets the minimum WordPress version to 5.2 and the minimum YoastSEO version to 12.6.
* We need the new HelpScout Beacon implementation that is in WPSEO 12.6.
* Install and activate Yoast SEO 12.5 and WooCommers, and build this branch of WooCommerce SEO. 
* Try to activate WooCommerce SEO. 
* See a notification.
* Install and activate Yoast SEO 12.6.
* Activate WooCommerce SEO.
* See no notification and see that WooCommerce SEO can be activated.
* Build this branch on a WordPress installation < 5.2.
* See a notification about the WP version.
Fixes #

Set minimum WP version to 5.2 and minimum YoastSEO version to 12.6

---

wpseo-woocommerce.php

Enable usage tracking.
*  None needed.
* Site should send tracking info if this plugin is enabled icw Yoast SEO free.

Enable usage tracking

---

.travis.yml

* _N/A_
Includes:
* Adjusting the Travis matrix now WP 5.3 has been released
* Removing the build against PHP 7.4 from `allowed failures`.
* Adding (back) a build against PHP `nightly` (PHP 8) and adding it to  `allowed_failures`.
For now, this build will only lint the code. Unit testing is not yet possible with  the current setup.
* Check the detailed travis script output

Travis: don't allow builds against PHP 7.4 to fail

---

.phpcs.xml.dist
.travis.yml
classes/option-woo.php
classes/woocommerce-schema.php
composer.json
composer.lock
integration-tests/bootstrap.php
integration-tests/classes/option-woo-test.php
integration-tests/woocommerce-seo-test.php
tests/TestCase.php
wpseo-woocommerce.php

* The `wpseo_woocommerce_og_price` filter hook has been deprecated in favour of the `Yoast\WP\Woocommerce\og_price` hook.
This updates the dependency in `composer.json`, as well as the PHPCS ruleset for YoastCS 2.0.0.
Includes:
* A selective update of the `composer.lock` for just YoastCS and its dependencies.
* Removing the tweaks to the Composer `check-cs` script to allow for different PHP requirements in different directories.
PHP 5.6 is now the minimum PHP version everywhere.
* Removing running the `config-yoastcs` script from the Travis script.
This hasn't been needed since YoastCS 1.1.0.
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.0.0
... which is no longer needed now PHP 5.6 is the minimum PHP version.
This …

PHPCS: Update to YoastCS 2.0.0

---

wpseo-woocommerce.php

* Fixes a bug where non-public taxonomies can chosen as manufacturer and brand.
*
* Checkout trunk
* In the admin settings you will see prominent words (when premium enabled) and two times tags.
* Checkout this branch
* Now you only see the public taxonomies.
Fixes #454

Filters the retrieved taxonomies to only have the viewable ones.

---

classes/woocommerce-schema.php

* Fixes a notice in the code that could happen on products with variations where a variation lacked an image.
* See reproduction steps in #466 
Fixes #466
Fixes https://github.com/Yoast/bugreports/issues/714

Fix a notice for empty image

---

wpseo-woocommerce.php

* When the shop page isn't set in WooCommerce, don't try to use it in the XML sitemap.
Fixes #401

If the shop page isn't set in Woo, don't try to use it in the XML sitemap

---

wpseo-woocommerce.php

* Adds `product:retailer_item_id` to the plugins OpenGraph output for Facebook Catalog usage.
* Fixes a bug where `product:availability` was set to `instock` instead of the correct `in stock`.
* Go to a product page, see the output now contains `product:retailer_item_id` and `product:availability` is set correctly.
Fixes #456

Adds SKU to the output, fixes instock to be in stock

---

tests/TestCase.php

* _N/A_
Classes used in namespaced files should always have a `use` statement.
* _N/A_

QA: add missing `use` statement for Mockery

---

tests/TestCase.php
tests/classes/schema-test.php

* _N/A_
Use fully qualified names for global functions to bypass PHP searching within the namespace first.
* _N/A_

QA: use FQN functions in namespaced files

---

classes/option-woo.php
classes/woocommerce-schema.php
classes/woocommerce-seo.php
integration-tests/classes/option-woo-test.php

* _N/A_
PHP has no concept of named return variables, so the name of the variable has no value in the `@return` tag.
* _N/A_
This is a documentation-only change and should have no effect on the functionality.

Docs: various improvements

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* When adding an ISBN number to a product, we double "type" it to `Book / Product`. By double typing it, the Product can have the attributes of both [schema.org/Book](https://schema.org/Book) _and_ [schema.org/Product](https://schema.org/Product), and thus it can have an `isbn` attribute and a `price` etc.
* Add an ISBN number to a product, see that the Schema output now contains `[ 'Book', 'Product' ]` as `@type`.

When a product has an ISBN, it's Schema technically a Book

---

classes/woocommerce-seo.php

* Currently, no product attributes are ever added to the Yoast SEO XML sitemap. With this fix, attributes which have archives _are_ added to the XML sitemaps.
* Create two product attributes. Set one to have archives, the other not to have archives. See that the former shows up in the XML sitemap while the latter doesn't.

Don't exclude product attributes from the XML sitemap by default

---

classes/woocommerce-seo.php

* When using the short description for the meta description and twitter and Facebook description, properly remove HTML tags and redundant spaces.
* See steps in https://github.com/Yoast/bugreports/issues/594
Fixes https://github.com/Yoast/bugreports/issues/594

Properly clean descriptions

---

classes/woocommerce-seo.php

* Do not output an empty `product:retailer_item_id` when there is no SKU.
* Have a product without an SKU, see that `product:retailer_item_id` is not in the OpenGraph output.
Fixes #496

Don't output empty retailer_item_id

---

classes/woocommerce-schema.php
classes/woocommerce-yoast-tab.php
tests/classes/woocommerce-yoast-tab-test.php

Allow saving empty value, issue existed only in non-released functionality, no changelog line needed.
* None needed.
* Set a GTIN8 or other value, save it. Then empty it, save again. See that it's saved as empty.
Fixes #495

Allow saving empty value for GTIN etc.

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* Remove `productID` from schema output. It adds complexity that isn't needed.
* See that `productID` no longer apears in schema output.
Fixes #500
Fixes #498

Remove productID from schema output

---

classes/woocommerce-seo.php

Make all product attributes available for Brands and Manufacturer dropdowns.
* Make all product attributes available for Brands and Manufacturer dropdowns instead of just product attributes with public archives.
* Create a product attribute, add some terms to it. Do not check the "Enable archives" box. 
* Go to SEO → WooCommerce. See that you can still select your new product attribute under Brands & Manufacturer. 
Fixes https://github.com/Yoast/bugreports/issues/872

Show all taxonomies in Brands & Manufacturer dropdowns

---

classes/woocommerce-seo.php

See https://github.com/Yoast/wpseo-woocommerce/pull/511
Applying same change to trunk.
* None needed.
* Applied the same change as in https://github.com/Yoast/wpseo-woocommerce/pull/511 to trunk, as merging it probably isn't possible cleanly anymore.
* See https://github.com/Yoast/wpseo-woocommerce/pull/511

12.5.1 fix to trunk

---

classes/woocommerce-yoast-tab.php

* Add explanatory copy above the input fields for GTIN, ISBN etc.
* Open the Yoast SEO tab in the WooCommerce product data metabox, see that there is now explanatory copy above the input fields.
FYI: the description is not 100% aligned with the title and field names. It's a conscious decision to not fix this by adding CSS to WooCommerce's page.

Add explanatory copy above product identifiers

---

tests/classes/woocommerce-yoast-tab-test.php
tests/doubles/opengraph-double.php

* QA: remove unused `use` statements
* QA: add missing class `use` import statement 
* QA: remove unused `use` statements
* QA: add missing class `use` import statement 
* _N/A_

QA: consistent use of `use` statements

---

tests/classes/opengraph-test.php
tests/classes/schema-test.php
tests/classes/utils-test.php
tests/classes/woocommerce-yoast-tab-test.php

* QA: declare static closures as static
* _N/A_

QA: declare static closures as static

---

tests/classes/opengraph-test.php
tests/classes/schema-test.php
tests/classes/utils-test.php
tests/classes/woocommerce-yoast-tab-test.php

* [Unit tests only] QA: use the most specific test assertion
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available has been extended hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for the Clicky plugin, while keeping in mind that at this time, PHPUnit 4.x should still be supported.
Refs:
* https://phpunit.de/manual/4.8/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* …

QA: use the most specific test assertion

---

js/src/yoastseo-woo-handle-excerpt-editors.js
js/src/yoastseo-woo-plugin.js

I know the fix seems silly, but the problem is that instead of throwing an error the code execution just stopped at the point where the function was called. This made it hard to pinpoint the exact point of failure.
* Fixes a bug where the internal linking and additional keyphrase functionality are missing from the product edit page.
*
* Make sure the Additional keyphrases and internal linking are visible and working correctly.
Fixes Yoast/Bugreports#881

Fix missing features in product editor

---

js/src/yoastseo-woo-handle-excerpt-editors.js
js/src/yoastseo-woo-plugin.js

* Fixes a bug where the internal linking and additional keyphrase functionality are missing from the product edit page.
* Cherry picked https://github.com/Yoast/wpseo-woocommerce/pull/516 to the release branch.
* `grunt build` and then open a product edit page.

Fix missing Premium functionality 

---

classes/woocommerce-opengraph.php
classes/woocommerce-schema.php

* N/A - Change the way we get the canonical by using the surface.
*
* Please test this against the features/indexables-frontend branch in Yoast SEO free
* Have WooCommerce active and add a product
* View the product and verify the canonical is in the WooCommerce schema output.
* In other words: there should be a Schema node with the type `ItemPage`, with an `@id` that is the same as the `<link rel="canonical>` on the page. 
Related to https://github.com/Yoast/wpseo-woocommerce/pull/439

Use surface for getting value

---

classes/woocommerce-schema.php
classes/woocommerce-utils.php
tests/classes/schema-test.php

* Fixes a bug where the `valueAddedTaxIncluded` property of the `Product` schema was set to `false` when the 'Yes, I will enter prices inclusive of tax' option was selected in WooCommerce. 
*
* Go to the WooCommerce tax settings.
* make sure that 'Display prices in the shop' is set to 'Including tax'.
* Go tot the WooCommerce SEO settings,
* make sure that 'Prices in OpenGraph and Schema include tax' is checked.
* Go to the WooCommerce general settings,
* make sure that 'Enable tax rates and calculations' is checked.
* Create a new WooCommerce product if you do not have one yet.
* Enter a price.
* Visit the WooCommerce product page of the product.
* Check the Schema code that is …

valueAddedTaxIncluded is not set to false when prices are added including tax

---

classes/option-woo.php
classes/woocommerce-schema.php
classes/woocommerce-seo.php
classes/woocommerce-utils.php
tests/classes/opengraph-test.php
tests/classes/schema-test.php
tests/classes/utils-test.php

* Fixes a bug where the product price and whether taxes were included were not accurately reflected in the Schema and Open Graph metatags.
* Removes the 'Prices in Open Graph and Schema include tax' setting in the plugin. Whether tax is included in Open Graph and Schema now solely relies on your product page settings in WooCommerce.
* The previous code only checked whether the entered price excluded tax and tax should be **added**. I added code to also check whether the price included tax and tax should be **subtracted** (if shop is set to exclude tax).
* Checkout and build the `master` branch of `wordpress-seo`.
* Checkout and build this branch of `wpseo-woocommerce`.
**TL,DR:** 
* …

Fix tax schema woocommerce

---

tests/classes/schema-test.php

* N/A
* Because `assertEquals` was recently changed to `assertSame`, the unit test failed because the schema properties were not in the right order. I changed the order of the properties to fix this.
* See that Travis passes.
Fixes #

Fix unit test

---

classes/option-woo.php
classes/woocommerce-schema.php
classes/woocommerce-seo.php
integration-tests/classes/option-woo-test.php
tests/classes/schema-test.php

* Adds a `color` attribute to the `Product` Schema output.
Product attributes in WooCommerce are custom attributes users may want to set. As far as I can tell, only `weight` and `dimensions` are default attributes and are part of the product _shipping_. Thus, the only way I could think of to get a product color is by doing the same thing we're doing for `brand` and `manufacturer`.
- adds a `Color` schema addition in SEO > WooCommerce SEO > Schema & OpenGraph additions
- users can create a product attribute and set it to be used as the Color addition
- the color Schema property is output as an array of colors, with lowercase color names
- adds a test for the product color output
- adjust existing tests
This PR can be tested by …

Add color property to the product schema output.

---

classes/woocommerce-seo.php
js/src/yoastseo-woo-replacevars.js
tests/classes/schema-test.php

* Adds the product identifiers (GTIN, ISBN etc.) to the SEO title and Meta description replacement variables.
- Please notice under the hood the product identifiers are custom fields. They belong to a specific product post. They will work only on the Edit product page, on a per product basis.
- While working on this I noticed a few things that look odd to me, will create separate issues.
- install / activate WooCommerce and wpseo-woocommerce
- switch wpseo-woocommerce to this branch and build
- publish a product making sure it has at least a price and it's in stock (so that it's actually visible on the front end)
- in the product snippet editor, add one or more (or all) the product …

Add replacement variables for product global identifiers

---

wpseo-woocommerce.php

* Removing the notification in WooCommerce that WooCommerce SEO is not tested with their 4.0 version.
* “We’ve tested with WooCommerce 4.0. Everything works as expected!”
*
* Install WooCommerce 3.9.
* Use this branch.
* See no notification telling WooCommerce SEO is not tested with Woo's 4.0 version.
Fixes https://github.com/Yoast/featurerequests/issues/471

Set WC tested up to version to 4.0

---

tests/classes/schema-test.php

* We want all of the unit tests to pass on `trunk`, to make sure that the quality of our code is the good and no bugs have been introduced.
* Fixes the `test_change_product_with_color` test.
* Fixes typo in `covers` annotations of the `add_color` method.
*
* Check that the unit tests pass.
Fixes #

Fixes `test_change_product_with_color` Schema tests on trunk

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* Fixes a bug where the `priceValidUntil` schema property wasn't output for products on sale with an explicitly set sale end date.
* Uses Woo methods `is_on_sale()` and `get_date_on_sale_to()`
* Unsets the `priceValidUntil` property except for products on sale with an explicitly set sale end date
* Adds a test
- create a Woo product
- set a regular price and save
- inspect the Schema output on the front end
- see there's no `priceValidUntil` property in the product Schema
- set a sale price but do not set the sale dates yet
- see there's still no `priceValidUntil` property in the Schema
- set the sales dates
- see this time there's a `priceValidUntil` property output in the Schema …

Output priceValidUntil for products on sale with a set sale end date

---

classes/woocommerce-opengraph.php
tests/classes/opengraph-test.php
tests/classes/schema-test.php

* Improve the Open Graph output for compatibility with what Pinterest expects. Also, handle `out of stock` and `backorder` statuses in addition to `instock`.
* Improves the Open Graph product availability for better compatibility with Facebook and Pinterest.
- deprecates `WPSEO_WooCommerce_OpenGraph->in_stock()`: **the deprecation is set for the 12.7 release**
- introduces `WPSEO_WooCommerce_OpenGraph->product_availability()` 
- introduces `WPSEO_WooCommerce_OpenGraph->pinterest_product_availability()` 
- both new methods handle the 3 stock statuses supported by WooCommerce: in stock, out of stock, on backorder
- adds tests
After some research, it appears this is a bit of a mess as Facebook and Pinterest expect different meta …

Improve Open Graph product availability

---

classes/woocommerce-seo.php
tests/classes/schema-test.php

* Please see https://github.com/Yoast/featurerequests/issues/426 and the test instructions on [the related PR](https://github.com/Yoast/wordpress-seo/pull/14497).
* Adds the term ancestors hierarchy as a taxonomy replacement variable.
Fixes https://github.com/Yoast/featurerequests/issues/426

Add term hierarchy as replacement variable.

---

classes/woocommerce-seo.php
js/src/yoastseo-woo-replacevars.js
tests/classes/schema-test.php

* To provide users with a better `price` replacement variable that outputs the correct price for regular price, sale price, grouped product price, variable product price.
* Improves the price replacement variable.
- makes sure to use Woo methods that take into account whether a product is on sale thus returning the sale price when appropriate 
- retrieves the product price also in the admin 
- uses the Woo `get_price_html` method for variable and grouped products so that we get a properly formatted _price range_ string
- puts the product price into the l10n object and use that for the snippet preview 
- the price in the snippet preview doesn't update "on the fly" any longer
To do in a separate issue:
- fix empty prices everywhere …

Improve the output of the price replacement variable

---

classes/woocommerce-seo.php

*  The image size of product gallery images should be the full size in the product XML sitemap.
* Fixes a bug where the thumbnail product gallery images (150x150) are added to the XML product sitemap instead of the full size images.
* Used the second parameter in `wp_get_attachment_image_src` (which determines size).
On trunk:
* Create a product
* At `Product gallery` click `Add product gallery images` and add multiple images 
* Publish
* Go to the product sitemap XML (http://basic.wordpress.test/product-sitemap.xml)
* Inspect the page source of the XML sitemap product page
* Notice that the **GALLERY** images are 150x150, i.e., that the `<image:loc>` sections contain a URL ending …

Implemented full image from gallery in xml sitemap

---

classes/woocommerce-schema.php

* We want to fix PHP notices and warnings shown on the front end.
* Fixes a bug where PHP notices and warning where thrown for Products without a price.
* 
- Install and activate Yoast SEO 13.4 RC3
- Install and activate Woocommerce 4.0.1
- Install and activate SEO Woocommerce switched to this branch
- Create empty product, do not add price
- Browse to the product on the front end
- Add a review
- See there are no PHP notices / warnings
Fixes https://github.com/Yoast/wpseo-woocommerce/issues/560

Check offers data exist before attempting to use it.

---

classes/woocommerce-schema.php

* Minor performance improvement
* Minor performance improvement
Above the `foreach` the `$prices_include_tax` variable is defined with the output of the same function call, so we may as well use it and remove the redundant repeated function call which would always have the same output anyway.
:arrow_right:  _Leaving this open for someone to quickly look this over in case I'm missing some context and the return value of the function call could change during the running of the loop._
* This PR should have no impact on the functionality, so the schema code added for offers should be the same before and after.

QA: use the variable

---

classes/option-woo.php
classes/woocommerce-seo.php
integration-tests/classes/option-woo-test.php
integration-tests/woocommerce-seo-test.php

* Simplify the plugin settings by prodiving sane defaults
* Hides all Yoast columns in the Product overview page except the SEO Score column.
- removes `woo_hide_columns` from the `wpseo_woo` option in the database
- removes related code used to validate the `woo_hide_columns` option
- adjusts existing test to check all columns except SEO Score aren't displayed
- activate and install Yoast SEO, WooCommerce, and WooCommerce SEO switched to this branch
- check in the database table `wp_options` > option_name `wpseo_woo` there's no `woo_hide_columns` 
- in the admin, go to SEO > WooCommerce SEO and see there's no UI to hide columns any longer (refer to the screenshot on the issue)
- go …

Hide all Yoast columns in the Product overview page except the SEO Score column

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* We want to users to not be able of entering possible harmful javascript code into the schema using the attributes
* Fixes a bug where possible harmful javascript could be entered in the database and affect a website.
* Chosen for `WPSEO_Utils::format_json_encode` over `json_encode` because it is conform the Yoast standards
* Chosen to remove the first and last character of the string if they happen to be double quotes, because otherwise the schema output would include 4 double quotes in total (""example"")
1. Install Yoast SEO (Premium), Woocommerce and wpseo woocommerce
2. Create a product attribute names `brand` and add a term called `banana`
3. In SEO -> WooCommerce SEO -> set …

Escape Attribute term

---

classes/presenters/woocommerce-abstract-product-presenter.php
classes/presenters/woocommerce-pinterest-product-availability-presenter.php
classes/presenters/woocommerce-product-availability-presenter.php
classes/presenters/woocommerce-product-brand-presenter.php
classes/presenters/woocommerce-product-condition-presenter.php
classes/presenters/woocommerce-product-opengraph-deprecation-presenter.php
classes/presenters/woocommerce-product-price-amount-presenter.php
classes/presenters/woocommerce-product-price-currency-presenter.php
classes/presenters/woocommerce-product-retailer-item-id-presenter.php

* There is no need to have `use` statements for no-namespaced classes. This might result in PHP warnings:
```
Warning: The use statement with non-compound name 'WPSEO_WooCommerce_Abstract_Product_Presenter' has no effect in /var/www/html/wp-content/plugins/wpseo-woocommerce/classes/presenters/woocommerce-product-price-currency-presenter.php on line 8 Call Stack: 0.0017 401912 1. {main}() /var/www/html/index.php:0 0.0030 402184 2. require('/var/www/html/wp-blog-header.php') /var/www/html/index.php:17 3.3847 7517880 3. require_once('/var/www/html/wp-includes/template-loader.php') /var/www/html/wp-blog-header.php:19 3.4056 7536616 4. include('/var/www/html/wp-content/plugins/woocommerce/templates/single-product.php') /var/www/html/wp-includes/template-loader.php:106 3.4056 7536616 5. …
```

Removal of the use statements

---

classes/woocommerce-opengraph.php
tests/classes/opengraph-test.php

* Remove the OpenGraph description override because that is already done in Yoast SEO itself.
*  Unifies the OpenGraph description callbacks as per https://developer.yoast.com/features/meta-tags/.
* Deprecate function.
* Remove/adjust related tests.
* Make sure you  have configured template for product categories:
* Start creating new product category with empty content, see that default template is applied:
* Publish category and check description tags (where before the `og:description` would be `content`):
```
<meta name="description" content="default" />
<meta property="og:description" content="default" />
```
Fixes #581

Remove OpenGraph description override

---

.phpcs.xml.dist
classes/presenters/woocommerce-product-opengraph-deprecation-presenter.php
tests/classes/presenters/pinterest-product-availability-presenter-test.php
tests/classes/presenters/product-availability-presenter-test.php
tests/classes/presenters/product-brand-presenter-test.php
tests/classes/presenters/product-condition-presenter-test.php
tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
tests/classes/presenters/product-price-amount-presenter-test.php
tests/classes/presenters/product-price-currency-presenter-test.php
tests/classes/presenters/product-retailer-item-id-presenter-test.php

* We want 100% code coverage in our tests.
* Adds tests for the presenters.
* WordPress action arguments should be an array, we previously sent a WC_Product. This is enforced through Brain Monkey. So to fix this I convert the WC_Product to an array in the deprecated action. -- The alternative would be that we do not test this.
* Temporarily disable the `Yoast.NamingConventions.ObjectNameDepth.MaxExceeded` sniff for the tests. The names seem fine as they are, Joost said to ignore it for now and Herre agreed with the temporary disabling as included here.
* Ensure the test coverage is 100%
* Have an opinion about the technical choice I made.
Fixes #577

Add presenter tests

---

classes/presenters/woocommerce-product-price-amount-presenter.php
classes/presenters/woocommerce-product-price-currency-presenter.php
classes/woocommerce-utils.php

* Avoid to output the lowest price and currency in the og meta `product:price:amount` for variable and grouped products.
* Omits the `product:price:amount` and `product:price:currency` og meta for variable and grouped products.
* introduced a utility method `get_product_type()`
* used that in the price amount presenter
- install and activate Yoast SEO, WooCommerce, and Yoast SEO: WooCommerce
- create a variable product with variations with different prices
- on trunk:
- see the product on the front end
- inspect the source and observe the meta `product:price:amount` outputs the lowest price
- observe there's a `product:price:currency` meta
- switch to this branch
- inspect the …

Omit the price amount and currency meta for variable and grouped products.

---

classes/woocommerce-opengraph.php
tests/classes/opengraph-test.php

* We want to improve the open graph image output when users set a specific image for a product.
* Fixes a bug where all product gallery images were used as open graph images even though users set a specific image for a product.
* Introduces a new method to check whether users set a specific image for a product, based on the `indexables` implementation. Hat tip to @hansjovis 
* Refactors most of the related tests to use a mocked instance of the main class to test.
- install Yoast SEO, WooCommerce, Yoast SEO: WooCommerce
- on trunk
- create a product and add some images in the "Product gallery" meta box
- add an image in the Yoast SEO meta box > Social > Facebook > Facebook Image
- …

Don't show open graph images gallery when image set by user

---

classes/woocommerce-seo.php
classes/woocommerce-twitter.php
tests/classes/twitter-test.php

* We want the Twitter image to fall back to the first image in the product gallery when no product image is set, to ensure that Twitter shows an image when sharing the webpage.
* Fixes a bug where the `twitter:image` meta tag did not fall back to the first product gallery image when no main product image was set.
* N/A
* Disable the open graph meta data 
* (set the 'Add Open Graph meta data' toggle to 'disabled' in _SEO_ > _Social_ > _Facebook_).
* Create a new WooCommerce product.
* Add multiple images to the product image gallery.
* Publish the product.
* Go to the frontend and check the HTML source code.
* The source code should have a `twitter:image` meta tag pointing to the URL …

Twitter image falls back to first image in product image gallery

---

classes/woocommerce-schema.php

* Non-user-facing due to only existing on trunk.
* Fixes a bug where the organization schema on for a primary term would error.
*
* Have a product with a manufacturer.
* Visit the frontend.
* No longer get an error due to term being null and trying to get name from null.
Fixes #

Fix getting name on null term

---

tests/classes/opengraph-test.php
tests/classes/twitter-test.php

* Code style consistency
* Code style consistency
These classes all have import `use` statements (or should have), so those should be used instead of the fully qualified name.
* _N/A_

QA: don't use FQN for an imported class

---

classes/woocommerce-schema.php

* Plugin shouldn't throw any PHP notices.
* Fixed potential undefined variable notice.
PR #588 (included in v 13.0.0) removed the `$prices_include_tax` variable, but it was still being used in the `if ( wc_tax_enabled() ) {` clause just below.
This brings back the variable to prevents those notices.
* Should be testable when the Woo install has product variants and offers.
* Toggle "prices have tax included" on/off.
* See the undefined variable notice in the PHP error logs.
* With this branch the notice should no longer be thrown.

Bug: fix undefined variable notice

---

classes/woocommerce-permalink-watcher.php

* The class `Yoast_Model` has been renamed and moved to another namespace.
* Fixes a bug where an non existing class is called.
*
* Have some products present and make sure there are indexables made for them
* Go to the permalink settings and change the structure for the product
* Visit your database and see the permalinks are set to null for the product indexables
Fixes #609

Call the right class

---

classes/woocommerce-schema.php
tests/classes/schema-test.php
tests/doubles/schema-double.php

* When the SKU of a product is left empty, WooCommerce makes it the value of the product's id. 
* Fixes a bug where an empty SKU fallbacks to the product's ID.
* Created a `filter_sku` function that is called in `change_product` in `woocommerce-schema.php`
* Checkout this branch and build
* Install Yoast SEO and Woocommerce
* Add a product (variable or simple)
* Leave SKU blank
* See that no SKU value is printed in the product graph in the source code
* Repeat the above steps on trunk and note that the sku value should be put out in the graph. 
Fixes https://github.com/Yoast/bugreports/issues/357

Sku incorrect value to blank

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* We want to improve the Product Schema to make the `availability` property accurate.
* Outputs a `PreOrder` value for the Product Schema availability property when the Product is "on backorder".
- filtered the availability value in the `filter_offers()` method
- added a test for the "on backorder" case and adjusted the existing tests
- install and activate Yoast SEO, WooCommerce, and Yoast SEO: WooCommerce
- create or edit a simple product
- in "Product data" meta box > Inventory, set the "Stock status" to "On backorder"
- view the product on the front end
- append the URL parameter `?yoastdebug` to the URL in your browser's address bar and press Enter to request again the page
- …

Alter schema availability for products on backorder.

---

tests/classes/schema-test.php

* The `valueAddedTaxIncluded` property was added, but never covered by tests.
* Adds a single test to cover the `valueAddedTaxIncluded` property.
* Added a single test to check that, if particular circumstances are met (i.e. `woocommerce_tax_display_shop` is set to `incl`), that the expected output is returned.
* Replaced the 'namespaced' calls to `expect` with a `use` statement, just to clean things up a tiny bit.
* Ensure all tests pass.
Fixes #552

P3-14 Added a single test for using the valueAddedTaxIncluded property

---

classes/woocommerce-seo.php
integration-tests/woocommerce-seo-test.php

* We want the Yoast SEO columns hidden by default (except SEO score) and users still able to make the visible.
Follow-up to https://github.com/Yoast/wpseo-woocommerce/pull/578/
* Makes the Yoast SEO columns hidden by default in the Products overview table.
The main point for this change is that the columns visibility is a _per-user_ setting. In order to make users able to set the columns visibility, this must be saved (and checked against) a user option. I used these WordPress functions:
- get_current_user_id()
- get_user_option()
- update_user_option()
I'd like to discuss with a senior dev / architect if this approach is OK. Also, this makes integration-tests a bit pointless, I guess.
This PR can be tested by following these …

P3-35 Make the Yoast SEO columns hidden by default

---

.travis.yml

This makes sure that the dependency injection container has been built and can be loaded.
* We want the integration tests to be able to run.
* Fixes a bug where the dependency injection container could not be installed in the Travis build when cloning and installing WordPress SEO.
* Instead of the normal development repository, the distribution version of WordPress SEO is now cloned and installed. 
* This means that the dependency injection container is already created and can be used out of the box.
* Check the Travis build. It should pass with flying (e.g. green) colors.
Fixes #

Travis now clones the distribution version of WordPress SEO

---

classes/woocommerce-seo.php

* Updates the plugin to the new Yoast styling.
*  Updates the plugin to the new Yoast styling.
*
* Build the plugin and get the `https://github.com/Yoast/wpseo-woocommerce/tree/FRO-211-woocommerse-styling-update branch` from the wordpress-seo repo.
* Install and activate Woocommerce
* Go the the Woocommerce page under SEO
* Check if the page uses the new styling
Fixes https://yoast.atlassian.net/browse/FRO-211

Update checkbox to new styling

---

classes/woocommerce-seo.php

* We want to cover the case were users may had set their custom settings for the Yoast columns and then they activate SEO Woo: in this case the user custom settings should not be changed. This way, new "defaults" are set only if the current setting is the "old defaults".
For reference, see the original issue https://github.com/Yoast/featurerequests/issues/464 
* Improves setting new defaults for the columns visibility in the Products overview page.
* checks if the current hidden columns user setting is the same as the old defaults, where these columns were the hidden ones:
- wpseo-title
- wpseo-metadesc
- wpseo-focuskw
- activate Yoast SEO and WooCommerce
- go to the Products page
- …

Set new hidden columns defaults only if user did not change the previous defaults

---

.travis.yml
README.md

* On August 11, WordPress 5.5 will be released. Because we always support the 2 latest versions, the minimum supported version needs to be updated to 5.4.
* Sets minimum supported WordPress version to 5.4.
*
*
Fixes #

Set minimum WP version to 5.4 and tested up to to 5.5

---

classes/woocommerce-seo.php
wpseo-woocommerce.php

*
* Enables tracking when activating the plugin. It can be disabled in the Yoast SEO configuration wizard.
*
* Make sure that the plugin is deactivated.
* Make sure that you have tracking disabled.
* You can do this in the Yoast SEO configuration wizard.
* Go to the Yoast SEO admin dashboard (click on _SEO_ in the admin sidebar menu).
* Click on the link titled _reopen the configuration wizard_.
* Open step 7 (_Help us improve Yoast SEO_).
* Select _No, I don't want to allow you to track my site data_.
* In your site's database, check the `wpseo` option in the `wp-options` table.
* Its `tracking` parameter in the serialized `option_value` should be set to `0` (no tracking).
* [You …

Enable tracking on plugin activation.

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

*
* Fixes a bug where the schema webpage type would be overwritten instead of added to.
*
* Go to the frontend of a product page.
* Check the schema `@type` of the `#webpage` graph piece.
* The `@type` should be `[ "WebPage", "ItemPage" ]`.
* Go to the admin edit of this page.
* Change the schema's page type and check that it is added as the `@type`.
* Go to the frontend of the checkout page (make sure you have something in your cart or you might be redirected to the cart page instead).
* Check the schema `@type` of the `#webpage` graph piece.
* The `@type` should be `[ "WebPage", "CheckoutPage" ]`.
* Change the schema's page type and check that it is added as the `@type`.
Fixes …

Add webpage type to types

---

classes/woocommerce-seo.php

*
* Fixes a bug where a fatal error would be thrown when Woo SEO would be activated when Yoast SEO (Premium) was not activated.
*
* Deactivate Woo SEO
* Deactivate Yoast SEO (premium)
* Activate Woo SEO
* See no fatal error
* Check that tracking is still activated.
Fixes https://yoast.atlassian.net/browse/QAK-2167

[QAK-2167] Check if WPSEO_Options exists before calling one of its methods

---

classes/woocommerce-seo.php
classes/woocommerce-slack.php
tests/classes/slack-test.php

* Yoast/wordpress-seo#16183 introduces a filter on the new Enhanced Slack data. We want to use this filter to show custom data for products.
* Hooks on the new Yoast SEO `wpseo_enhanced_data` filter to show product data whan sharing on Slack
* The translations for "Price" and "Availability", as well as "In stock, "On backorder" and "Out of stock", could be taken from the WooCommerce translations instead of duplicating the strings in the Yoast WooCommerce SEO dictionary, but this not allowed by CS
* Checkout and build, making sure you have using Yoast SEO in which Yoast/wordpress-seo#16183 has been merged.
* Visit a product on the front end and inspect the source.
* check that just …

P3-204 improve slack sharing of products

---

classes/woocommerce-slack.php
tests/classes/slack-test.php

* The Enhanced Slack sharing feature is currently broken on products that are "On back order"-
*  Fixes a bug where the Enhanced Slack sharing showed wrong availability for products on backorder
* This happened beacuse `product->is_in_stock()` returns `true` for backorder products too, so it must be checked first.
* Checkout and build, making sure you have using Yoast SEO in which Yoast/wordpress-seo#16183 has been merged (`release/15.2` will be fine) + WooCommerce with some products
* Visit a product which is on backorder on the front end and inspect the source.
* check that just before the schema there are tags like these ones:
```
<meta name="twitter:label1" value="Price">
<meta …
```

P3-239 Fix checking for backorder

---

.phpcs.xml.dist
composer.json
config/composer/actions.php

* Introduces the `composer cs` command; as also present in Yoast SEO
* Tooling: introduces the `composer cs` command
* Adjusted CS configuration to handle the config folder; inspired on Yoast SEO
* Created a config directory
* Removed the `yoast-configcs` command; which is no longer needed
* Run `composer install`
* Run `composer cs` and get a menu to pick which check you want to perform
* Perform any of the menu options and see them working as expected
Fixes #

Introduce `composer cs` command

---

classes/woocommerce-slack.php
tests/classes/slack-test.php

*
* Hooks to the renamed enhanced Slack data filter.
*
* needs https://github.com/Yoast/wordpress-seo/pull/16242 to be merged
* refer to instructions on https://github.com/Yoast/wpseo-woocommerce/pull/639 for testing
Fixes #

Rename enhanced Slack data filter

---

.travis.yml
composer.json
composer.lock
tests/classes/schema-test.php

* Updated dev dependencies
* Updated dev dependencies
* Updated YoastCS from `2.0.2` to `2.1.0`.
* Updated PHP_CodeSniffer from `3.5.5` to `3.5.8`.
* Updated the DealerDirect Composer plugin from `0.6.2` to `0.7.0` (which is compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Relevant changes in PHPCS:
* PHPCS will now _run_ without problems on PHP 8.
Note: it will not necessarily handle all code using PHP 8 syntax correctly yet, though it does contain preliminary support for various syntaxes.
* Lots of bugfixes.
Refs:
* …

Composer: update YoastCS to v 2.1.0

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* https://yoast.atlassian.net/browse/P2-504
* Makes the Schema `Product` type filterable.
* I looked for all occurrences of the filter `woocommerce_structured_data_***` in the code and found these three:
* `woocommerce_structured_data_product`.
* `woocommerce_structured_data_type_for_page`.
* `woocommerce_structured_data_review`.
* The `woocommerce_structured_data_product` filter triggers the `change_product` method, which changes the Schema `Product` type. I added a call to our `wpseo_schema_product` filter to make the `Product` type filterable.
* The `woocommerce_structured_data_type_for_page` filter triggers the `remove_woo_breadcrumbs` method, which removes the Woo breadcrumbs from the Schema output. I did not add a call to a …

Apply the wpseo_schema_product filter to make the Product type filterable

---

composer.json
composer.lock
tests/classes/opengraph-test.php
tests/classes/schema-test.php
tests/classes/woocommerce-yoast-tab-test.php

* Updated test dependency
* Updated test dependency
Updated:
* BrainMonkey from v 2.4.0 to 2.5.0.
Note: this version contains a test breaking change which will be addressed in a subsequent commit if applicable for this repo.
* Mockery from v 1.3.0 to 1.3.3.
Improved support for PHP 8.
* Hamcrest-php from v 2.0.0 to 2.0.1
... which claims compatibility with PHP 8.
* Patchwork from v 2.1.11 to 2.1.12
This fixes [two issues](antecedent/patchwork#99) which _might_ be relevant for us.
Refs:
* https://github.com/Brain-WP/BrainMonkey/releases
* https://github.com/mockery/mockery/releases
* https://github.com/hamcrest/hamcrest-php/releases
* https://github.com/antecedent/patchwork/releases
The WP native `has_filter()` function returns a …

Composer: update BrainMonkey with dependencies

---

tests/classes/schema-test.php

* Code consistency
* Code consistency
Don't import namespaced functions. Import the namespace instead.
* _N/A_. If the tests still pass, we're good.

QA: don't import namespaced functions

---

.gitignore
.travis.yml
composer.json
composer.lock
phpunit.xml.dist
tests/TestCase.php
tests/bootstrap.php
tests/classes/opengraph-test.php
tests/classes/presenters/pinterest-product-availability-presenter-test.php
tests/classes/presenters/product-availability-presenter-test.php
tests/classes/presenters/product-brand-presenter-test.php
tests/classes/presenters/product-condition-presenter-test.php
tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
tests/classes/presenters/product-price-amount-presenter-test.php
tests/classes/presenters/product-price-currency-presenter-test.php
tests/classes/presenters/product-retailer-item-id-presenter-test.php
tests/classes/schema-test.php
tests/classes/slack-test.php
tests/classes/twitter-test.php
tests/classes/woocommerce-dependencies-test.php
tests/classes/woocommerce-yoast-tab-test.php

* Preparation for compatibility with PHP 8
* Preparation for compatibility with PHP 8
Similar to the other test update PRs, this PR will be easiest to review by looking at each commit individually.
* Adds a dev dependency to the `yoast/wp-test-utils` package, which will also make the PHPUnit Polyfills available.
* As that package already requires and manages the installable versions for BrainMonkey and PHPUnit, remove these as explicit requirements from `require- dev` in favour of letting the WP Test Utils package manage the versions.
The install is done based on PHP 5.6 and includes updating the dependencies from PHPUnit itself within the constraints of maintaining compatibility with  PHP 5.6.
This new package adds the following …

Unit Tests: make the testsuite compatible with PHPUnit 9 and test against PHP 8

---

.travis.yml
composer.json
composer.lock
integration-tests/bootstrap.php
integration-tests/classes/option-woo-test.php
integration-tests/framework/woocommerce-unittestcase.php
phpunit-integration.xml.dist

* (Preparation for) compatibility with PHP 8
* (Preparation for) compatibility with PHP 8
:bulb: This PR will be easiest to review by going through the individual commits one by one.
As there is a `autoload-dev` in place, the Composer autoloader will automatically include the files.
Includes removing a method which has now become redundant.
A new version of the WP Test Utils package has been released which deals with the necessary work-arounds for the WP integration tests and adds utilities for this which individual plugins can use, like functions for the bootstrap and a `TestCase` which includes all the polyfills from the PHPUnit Polyfill repo.
The install is done based on PHP 5.6 (`config.platform.php` is set in the …

Integration Tests: make the testsuite x-version compatible and test against PHP 8

---

tests/TestCase.php
tests/classes/presenters/pinterest-product-availability-presenter-test.php
tests/classes/presenters/product-availability-presenter-test.php
tests/classes/presenters/product-brand-presenter-test.php
tests/classes/presenters/product-condition-presenter-test.php
tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
tests/classes/presenters/product-price-amount-presenter-test.php
tests/classes/presenters/product-price-currency-presenter-test.php
tests/classes/presenters/product-retailer-item-id-presenter-test.php
tests/classes/schema-test.php
tests/classes/woocommerce-dependencies-test.php
tests/classes/woocommerce-yoast-tab-test.php

* Improve test quality
* Improve test quality
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available have been extended hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for this plugin.
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertSame
PHPUnit contains a native `expectOutputString()` and a …

Tests: improve used assertions and expectations

---

classes/presenters/woocommerce-schema-presenter.php
classes/woocommerce-schema.php
tests/classes/schema-test.php
yarn.lock

* The old code used `WPSEO_Utils::schema_output`, which we deprecated.
* Fixes a bug where a deprecation notice would be shown in the PHP debug log when visiting a product page.
* Added a new presenter, since...
* the graph has already been generated and can be passed directly to the presenter.
* the `Schema_Presenter` does not have the ability to add additional classes to the `script` tag.
* Starting with a vanilla installation: (debug logging enabled)
* Install, activate, and set up WooCommerce. (options below)
* Install and activate Yoast SEO (free or premium)
* Install and activate Yoast SEO WooCommerce
* Go to Admin > Products
* View a product
* Check the source code …

Added schema presenter.

---

tests/classes/presenters/schema-presenter-test.php

*
* Adds unit tests for the newly introduced `WPSEO_WooCommerce_Schema_Presenter`.
*
* Run unit tests with code coverage enabled.
* See that all of the unit tests pass and the code coverage of `WPSEO_WooCommerce_Schema_Presenter` is 100%.
* N/A, this PR just adds extra unit tests. It does no impact any functionality within the plugin.
* N/A, this PR just adds extra unit tests. It does no impact any functionality within the plugin.
Fixes #

Added unit tests for WooCommerce schema presenter.

---

classes/woocommerce-seo.php

* As a followup to https://github.com/Yoast/wordpress-seo/pull/16615 this switches the news plugin to a filter instead of loading the HelpScout class separately.
* Improve how we load HelpScout
*
* The beacon should still load with this patch applied.
*
*
Fixes #

Improve how we load HelpScout

---

classes/woocommerce-seo.php
config/webpack/webpack.config.default.js
js/src/yoastseo-woo-plugin.js
package.json
yarn.lock

* We want our Google Preview to reflect how the search result for a product looks in Google. So when the necessary data for Product schema is available, it should show up in the Google Preview, like this:
* When used together with the latest version of Wordpress SEO or Wordpress SEO Premium, the Google Preview for products now shows the rating, number of reviews, price and availability like in Google.
* For the sake of simplicity we decided to directly dispatch to the WPSEO store.
* Since the needed data is not yet available in WooCommerce's stores, this data is static for now.
* Test together with the related branches on Free and the Monorepo, of for QA with the latest …

P1 345 woocommerce snippet in google preview

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* Change the Schema output generated for product price specifications to prevent warnings from Google Search Console.
* See JIRA issue PRODUCT-252 for the change.(Note by Andrea: PRODUCT-252 just redirects to P3-464 now)
* install and activate Yoast SEO, WooCommerce, and Woo SEO (switched to this branch and built)
* create a new Product
* in the "Product data" meta box, keep the default type "Simple product", add a price, and publish
* check the Product Schema output in the front end (note that it's separate from the main Schema output)
* note that a simple Product has only one "offer" entry with a `"@type"` value of `"Offer"`
* check the `priceSpecification` property …

P3-464 Fix product price schema output

---

classes/woocommerce-seo.php

* The Availability string that was dispatched to WP SEO had dashes between words. That needs to be spaces.
* Replaces hyphens in the WooCommerce availability status with spaces.
* Replaces the "available on backorder" in the WooCommerce availability status with "preorder", because that is what is output on the frontend. Backorder is not a value supported by Google.
*
* Checkout this branch together with WP SEO 16.3-beta or Trunk and the P1-488 branch of the Javascript monorepo
* Or for QA, use the latest 16.3 beta of WP SEO, that has the monorepo change in it.
* Edit a Product and check whether in the Google preview, the description of the Availability is written with a …

P1-488 Shoppingdata Availability typography

---

js/src/yoastseo-woo-plugin.js

* A product gallery image should override the site wide default OG image.
* Fixes an unreleased bug where a Product Gallery image would not have priority over the site-wide default OpenGraph image in the Social Previews.
*
* Test together with Premium (16.3).
* Set a "site-wide" default OG image, in SEO -> social -> Facebook.
* Add a new product in WooCommerce.
* Navigate to the Social Previews.
* Verify that, without any further images on the page (no content image, no product image, no product gallery image), the sitewide image you just set is visible in the previews.
* Now, as you add the following images, they should override the default preview image in order:
* Add …

Output a product gallery image before defaulting to the site-wide social default

---

classes/option-woo.php
classes/woocommerce-permalink-watcher.php
classes/woocommerce-seo.php
config/composer/actions.php
tests/classes/presenters/product-price-amount-presenter-test.php
tests/classes/presenters/product-price-currency-presenter-test.php
tests/classes/presenters/schema-presenter-test.php
tests/classes/schema-test.php
tests/classes/woocommerce-dependencies-test.php
tests/classes/woocommerce-yoast-tab-test.php

* Code consistency
* Code consistency
Always use `use` import statements for a class or a namespace, not for functions or constants directly to make it more obvious where something is coming from in the code.
As per Yoast/yoastcs#215
... if the if statement is the only thing within the `else`.
This doesn't change anything functionally and simplifies the code.
The name of a return value does not get passed on, so has no significance in the docs.
.. for global functions and constants in namespaced files.
... to prevent using a reserved keyword as a parameter name.
While this isn't forbidden, in PHP 8.0+ with named parameters this can lead to very confusing code, so better to use another name.
This PR can be acceptance tested by …

CS/QA: various minor fixes

---

classes/woocommerce-seo.php

* WooCommerce has an option to disable ratings or reviews. When one of those is disabled, we don't output schema for both the rating and the reviewCount. The Google preview should reflect this.
* We displayed the number of ratings in our Google preview, that needed to be the number of reviews like er output in our Schema. 
* Fixes an unreleased bug where after disabling the rating or reviews in WooCommerce, they still were present in our Google Preview.
* Fixes an unreleased bug where the number of ratings was displayed in our Google Preview instead of the number of reviews.
*
* Enable this branch or latest RC of SEO for WooCommerce and WordPress SEO 16.3(RC)
* In …

P1 511 rating outputs disabling

---

js/src/yoastseo-woo-plugin.js

* We want to update the product gallery image fallback logic to take into account the upcoming Social default image.
* Updates the the product gallery image fallback logic to take into account the Social default image.
*
**Prerequisites:**
- activate Yoast SEO Free, switched to the `P3-574-social-templates-previews` branch and build it
- activate Yoast SEO Premium trunk and build it
- activate WooCommerce 
- activate Woo SEO, switched to this branch `P3-600-update-filtering-social-images-fallback` and build it 
- make sure the Global Social Template feature flag is enabled by setting this constant in your wp-config.php file: `define( 'YOAST_SEO_SOCIAL_TEMPLATES', true );` …

Update filtering of the social images fallback.

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* updates the required plugin version for woocommerce to 16.4.
*
* Build the plugin in Docker from this PR's branch
* Install and activate `WooCommerce` 
* In case `Yoast SEO: WooCommerce` is not activated, activate it
* Install and activate `Yoast SEO Free 16.3`
* You should read a warning to upgrade the Free plugin on the top of the Plugins page (/wp-admin/plugins.php)
* Replace `Yoast SEO Free 16.3` with the latest 16.4 RC
* Check that you don't get the warning message
*
*
Fixes #

LINGO-848 Update plugin version to 16.4 

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

* We support the last two released versions of WordPress.
* Sets the minimum WordPress version to 5.6.
*
* No need to test this PR.
*
*
Fixes #

Set the minimum required WP version to 5.6

---

.travis.yml
classes/presenters/woocommerce-abstract-product-presenter.php
classes/presenters/woocommerce-pinterest-product-availability-presenter.php
classes/presenters/woocommerce-product-availability-presenter.php
classes/presenters/woocommerce-product-brand-presenter.php
classes/presenters/woocommerce-product-condition-presenter.php
classes/presenters/woocommerce-product-price-amount-presenter.php
classes/presenters/woocommerce-product-price-currency-presenter.php
classes/presenters/woocommerce-product-retailer-item-id-presenter.php
classes/woocommerce-dependencies.php
classes/woocommerce-seo.php
composer.json
composer.lock
tests/classes/presenters/pinterest-product-availability-presenter-test.php
tests/classes/presenters/product-availability-presenter-test.php
tests/classes/presenters/product-brand-presenter-test.php
tests/classes/presenters/product-condition-presenter-test.php
tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
tests/classes/presenters/product-price-amount-presenter-test.php
tests/classes/presenters/product-price-currency-presenter-test.php
tests/classes/presenters/product-retailer-item-id-presenter-test.php
tests/classes/presenters/schema-presenter-test.php
tests/classes/schema-test.php
tests/classes/woocommerce-dependencies-test.php

* Made WooCommerce SEO compatible with new Abstract Indexable Tag Presenter in free 16.7
* Adds support for the headless functionality introduced in Yoast SEO 16.7.
* Bumps the minimum required version for Yoast SEO to 16.7.
* If you delete your primary location without updating your primary location in the Local SEO settings, ánd you have only one location left, meta tags will fall back to use this location instead.
* added key and tag format to make the presenter compatible with the Abstract_Indexable_Tag_Presenter that's new in free 16.7
* Check out https://github.com/Yoast/wordpress-seo/tree/release/16.7
* Create a WooCommerce product
* Inspect the front end and make …

P2-1091 implement abstract indexable tag presenter

---

classes/woocommerce-seo.php

* Fixes https://yoast.atlassian.net/browse/P2-1148
* Fixes https://yoast.atlassian.net/browse/P2-1149
* Fixes a bug where a fatal error was thrown on the frontend of product pages when using the `%%wc_shortdesc%%` snippet variable while running PHP 8.0.
* Fixes a bug where the `%%wc_price%%`, `%%wc_sku%%`, `%%wc_shortdesc%%` and `%%wc_brand%%` snippet variable values were not displayed on the frontend.
* Added a fallback in the get_product() method for cases where $context is not used in the get_method() call
* Added a fallback for cases where get_product returns null in the get_product_short_description() method, to avoid potential Fatal Errors in PHPv8.0
* The `YoastSEO()` surface will always be available, because the minimum …

Add fallback when context is null and also fallback when product is null (also fixes: P2-1149)

---

classes/woocommerce-seo.php

* 
* Fixes a bug where the product identifier replacement variables `%%wc_gtin8%%`, `%%wc_gtin12%%`, `%%wc_gtin13%%`, `%%wc_gtin14%%`, `%%wc_isbn%%` and `%%wc_mpn%%` would not work in meta descriptions when retrieving posts using REST requests.
* 
For acceptance testers:
* The WooCommerce SEO dev environment is currently broken. See [this issue](https://yoast.atlassian.net/browse/P2-1151) and [this PR](https://github.com/Yoast/wpseo-woocommerce/pull/704).
* A workaround is to remove `wordpress-seo` from the `composer.json` temporarily.
* You can do this by executing this command: `composer remove --dev yoast/wordpress-seo`.
* Do not commit these changes, but remove them …

Cache product identifiers, make sure that they are always available.

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Sets the minimum required Yoast SEO version to 17.1.
* In 17.1 we introduced the specfic product analysis.
* Install and activate `WooCommerce` 
* In case `Yoast SEO: WooCommerce` is not activated, activate it
* Install and activate `Yoast SEO Free 17.0`
* You should read a warning to upgrade the Free plugin on the top of the Plugins page (/wp-admin/plugins.php), see screenshot below.
* Replace `Yoast SEO Free 17.0` with the latest 17.1 RC
* Confirm that you don't get the warning message
*
*
Fixes …

Up the required Yoast SEO version

---

js/src/initializers/product-assessor.js

* Our video count in the images assessment is based on `video` tags. However, these tags aren't added when we add a video from a URL (e.g., linking a Youtube video). So those videos aren't recognized in the assessment, which results in incorrect feedback. For this reason, we will exclude videos in Images assessment in WooCommerce.
* Excludes videos in Images assessment in WooCommerce product pages analysis.
*
This PR should be tested with [its accompanying PR](https://github.com/Yoast/wordpress-seo/pull/17381) in Free.
* Build the Free plugin 
* Run ` composer require yoast/wordpress-seo:dev-LINGO-1011-exclude-videos-from-images-assessment-in-woo@dev`
* Build WooCommerce …

Exclude videos in Images assessment in Woo product pages

---

classes/woocommerce-seo.php
tests/classes/opengraph-test.php
tests/classes/presenters/pinterest-product-availability-presenter-test.php
tests/classes/presenters/product-availability-presenter-test.php
tests/classes/presenters/product-brand-presenter-test.php
tests/classes/presenters/product-condition-presenter-test.php
tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
tests/classes/presenters/product-price-amount-presenter-test.php
tests/classes/presenters/product-price-currency-presenter-test.php
tests/classes/presenters/product-retailer-item-id-presenter-test.php
tests/classes/seo-trait.php
tests/classes/slack-test.php
tests/classes/twitter-test.php
tests/doubles/schema-double.php

* Code consistency
* Code consistency
Various minor tweaks:
* Alignment of `@param` tags.
* Add missing (default) type to `@param` tag.
* Import all `use`d classes/interfaces, including when only used in docblocks.
* Order `use` statements alphabetically.
* Ignore a (known) false positive from YoastCS.
* _N/A_ if the build passes we're good (and it won't, but that's not due to this change, the CS part passes)

CS: clean up after merges

---

composer.json

*
*
The `vendor` directory is already ignored via the YoastCS ruleset, so no need to explicitly ignore it.
* _N/A_ If the (CS part of the) build passes, we're good.

Composer: clean up CS command

---

.travis.yml
composer.json
composer.lock
phpunit-integration.xml.dist
phpunit.xml.dist

* Update test setup
* Updates test setup
See the [Make Core dev-note about the test changes](https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/) for the context of these changes.
PHPUnit recently released version 9.5.10 and 8.5.21.
This contains a particular (IMO breaking) change:
> * PHPUnit no longer converts PHP deprecations to exceptions by default (configure `convertDeprecationsToExceptions="true"` to enable this)
Let's unpack this:
Previously (PHPUnit < 9.5.10/8.5.21), if PHPUnit would encounter a PHP native deprecation notice, it would:
1. Show a test which causes a deprecation notice to be thrown as **"errored"**,
2. Show the **first** deprecation notice it encountered and
3. PHPUnit …

Update (fix) test setup

---

composer.lock

* Updated dev dependencies
* Updated dev dependencies
Update various dev dependencies:
* PHP_CodeSniffer from 3.6.0 to 3.6.1
* BrainMonkey from 2.6.0 to 2.6.1
* Patchwork from 2.1.15 to 2.1.17
* PHPUnit Polyfills from 1.0.2 to 1.0.3
* YoastSEO Free - trunk branch update
* Composer Installers from 1.11.0 to 1.12.0
Refs:
* https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.6.1
* https://github.com/Brain-WP/BrainMonkey/releases/2.6.1
* https://github.com/antecedent/patchwork/releases/tag/2.1.17
* https://github.com/antecedent/patchwork/releases/tag/2.1.16
* https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.0.3
* https://github.com/composer/installers/releases/tag/v1.12.0
This PR can be acceptance tested by following …

Composer: update dev dependencies

---

classes/woocommerce-dependencies.php
composer.json
composer.lock
yarn.lock

* We had a breaking change in Assessors.
* The wpseo-woocommerce js contains some js from the `yoastseo` package in which the BC break happend. That's why we need to update our dev-dependency of Yoast SEO free (which includes `yoastseo`) and rebuild our javascript.
* Ensure compatibility with Yoast SEO Free 17.8.
* Sets the minimum required Yoast SEO version to 17.8.
* 
* (if not RC testing) run `composer install`, `yarn install` and `grunt build`
* Install Yoast SEO Free > 17.8-RC0 and the latest version of WooCommerce
* Edit a product page
* See that the product-specific SEO assessments load and that you get an error in the browser console. The error has `Cannot read …

Build js with latest version of yoastseo

---

config/webpack/webpack.config.default.js

* Calls to `__()` inside classes that were imported from `yoastseo` inside the worker didn't use the same instance of i18n, which caused them to not be translated properly.
* Fixes an unreleased bug where the content analysis was partially not translated for products.
*
* Change the site language to something other than English.
* Edit or create a WooCommerce Product, add 400 words, check analysis - check that all elements in the content analysis are translated.
*
* (Javascript) translations in the product edit page.
Fixes QA-2665

Externalize i18n

---

.travis.yml
composer.json
composer.lock

* Composer 2.2 compatibility
* Composer 2.2 compatibility
The `dealerdirect/phpcodesniffer-composer-installer` Composer plugin is used to register external PHPCS standards with PHPCS.
The `composer/installers` Composer plugin is used to install the plugin in the correct directory in a WordPress context.
As of Composer 2.2.0, Composer plugins need to be explicitly allowed to run. This adds the necessary configuration for that.
Refs:
* https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution

Composer: allow the PHPCS plugin

---

.travis.yml

* Simplify CI
* Simplify CI
Follow up on #736
This reverts commit c9e91bf816443ee6dd8b474e692b2577b894b84b.
Composer 2.2.3 has been released which contains a fix for the overly greedy optimization pass which was introduced in Composer 2.2.0.
With this fix in place, the previously introduced work-around for Composer 2.2 is no longer needed.
Refs:
* https://github.com/composer/composer/releases/tag/2.2.3
* https://github.com/composer/composer/issues/10394
* _N/A_ If the build passes, we're good.

Travis: remove "fix PHP 8.0 build icm Composer 2.2"

---

js/src/assessments/ProductDescriptionAssessment.js
js/tests/assessments/ProductDescriptionAssessment.test.js

* We were unable to adapt the configuration for product description length. This PR allows to pass a custom configuration. 
* Also, the production description length is now counted in characters for languages that have a `customCountLength` helper defined. 
* Adapts Product description assessment for Japanese.
*
Requirements:
* Install and activate WooCommerce plugin
* Build the Yoast SEO WooCommerce plugin
**Test in English** (to make sure that the assessment is still working as expected after the changes are introduced)
* Set the site language to English
* Create a Product (don't add a short description yet)
* Confirm that the feedback below is shown under SEO analysis …

Made configuration for product description length adaptable

---

.github/workflows/integrationtest.yml

* We used to test against 5.9 RC3, now 5.9 is released, we can use "latest" again with PHP 8.1 tests
* Run automated tests with WordPress 5.9
* The WP5.9+PHP8.1 test case matches [the description of type 1](https://github.com/Yoast/wpseo-woocommerce/blob/79711b252d4224d3de16fbca1b6f345c2beeab2b/.github/workflows/integrationtest.yml#L92). I now consider the "latest" version to be type 1, as all future latest versions will of course be > 5.9.
* See integration tests pass with WP 5.9 and PHP 8.1
*
*

Run integration tests with WP 5.9

---

.github/workflows/integrationtest.yml
README.md
classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

* On January 25, 2022, WordPress 5.9 was released. We've decided to go back to supporting only the latest 2 WP versions.
* Sets minimum required WordPress version to 5.8.
*
* Have WordPress 5.7 or lower installed. Be unable to update.
* See all github actions succeed.
*
*
Fixes #

Set minimum WP version to 5.8 and tested up to to 5.9

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Sets the minimum required Yoast SEO version to 18.4.
*
*
*
*
Fixes #

DUPP-318 Bump minimum required Free version to 18.4-RC0

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/integrationtest.yml
.github/workflows/js.yml
.github/workflows/lint.yml
.github/workflows/security.yml
.github/workflows/unittest.yml

* Improve CI
* Improve CI
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases
... across all workflows in all repos.
This token has access to both the Yoast organisation as well as the Yoast-dist organisation.
* _N/A_ If the build passes, we're good.

GH Actions: minor updates

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

*
* Makes WooCommerce SEO compatible with the schema changes introduced in Yoast SEO 18.5.
*
* Install Free 18.5
* Publish a product with a Product Image
* Visit the product's frontend and copy all of the source code and run it in the https://validator.schema.org/ validator
Without this PR:
* Visit the product's frontend and copy all of the source code and run it in the https://validator.schema.org/ validator
* You'll get an `Unspecified Type` as a result:
With this PR:
* Visit the product's frontend and copy all of the source code and run it in the https://validator.schema.org/ validator
* You are NOT going to get an `Unspecified Type` as a result:
This PR affects the …

Schema output for Product is not correct and contains Unspecified Type

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

Reverts Yoast/wpseo-woocommerce#759

Revert "Schema output for Product is not correct and contains Unspecified Type"

---

classes/woocommerce-seo.php

* In Yoast/wordpress-seo#18344 the title and alt properties were removed. This means that adding them to the $image no longer serves a purpose.
* Removes XML sitemap image properties `title` and `caption` following deprecation by Google.
* Create a product with a product image gallery with images with an alt text and title.
* Open the products sitemaps and see that the product images.
* See that the `<image:title>` and `<image:caption>` no longer appear in XML sitemaps for all products, including the new product.
* n/a
Fixes PRODUCT-668

DUPP-469 Remove deprecated sitemap properties for product images

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Sets the minimum required Yoast SEO version to 18.8.
*
*
*
*
Fixes

 Bump minimum required Free version to 18.8-RC0

---

.github/workflows/integrationtest.yml
README.md
classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

* Sets minimum WordPress version to 5.9 and tested up to 6.0.
* Sets minimum WordPress version to 5.9 and tested up to 6.0.
*
*
*
*
Fixes #

Sets minimum WordPress version to 5.9 and tested up to 6.0.

---

classes/woocommerce-schema.php
composer.json
composer.lock
tests/classes/schema-test.php

* We want to enrich generated products' schemata by adding more information  related to products' variations
* Adds variations' SKU and URL to a product's schema. Props to @jaredforth.
* N/A
* Create some variations of a product and specify the price for each variation. **Note:** At least one variation needs to have a different price than the others for the proper `AggregateOffer` schema piece to be generated
* For some of the variations, fill the SKU input field too
* Check the frontend of the product you created and find the schema having `Product` as `@type` 
* Validate the schema through a schema validator tool (e.g. [this](https://classyschema.org/Visualisation))
* …

DUPP-401 - DUPP-401-add-variations-sku-and-url-to-schema

---

.github/workflows/integrationtest.yml
README.md
classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

* We want to support WP 5.8 a little longer after the release of 6.0
* Sets minimum WordPress version back to 5.8.
*
*
*
*
Fixes #

Sets minimum WordPress version back to 5.8

---

classes/woocommerce-yoast-ids.php
tests/classes/woocommerce-yoast-ids-test.php

* In [this PR](https://github.com/Yoast/wpseo-woocommerce/pull/761/commits/c6d1beee0d50bd543629741f695f5345098680c6) the id name for product variants identifiers was accidentally misspelled. 
* Edits typo in id name for product variants identifiers.
*
* Create a product and make some variations for it
* Open the variations and confirm that the fields related to global identifiers are showing
* Right click on of the identifier fields and choose `Inspect` from the drop-down menu
* An `Element` console will open to the right of the screen
* In that `Element` console, confirm that the name you see in the id field is `yoast_variation_identifier` (and not …

edit typo in variants identifier name

---

.github/workflows/deploy.yml

* CI maintenance
* CI maintenance
Ensure that `coverage: none` is always used (except for when running Coverage) as it prevents problems with undesired extensions being installed/incorrectly configured.
`setup-php` has deprecated and replaced an environment variable in a recent release:
> Deprecated COMPOSER_TOKEN in favor of GITHUB_TOKEN
This updates the workflow for that change.
Refs:
* https://github.com/shivammathur/setup-php/releases/tag/2.21.0
* https://github.com/shivammathur/setup-php#github-composer-authentication
* _N/A_ If the build passes, we're good.

GH Actions: minor tweaks

---

classes/woocommerce-yoast-ids.php
classes/woocommerce-yoast-tab.php

* Minor security improvement
* Minor security improvement
`esc_attr*()` should be used for values in HTML attributes and attributes should be escaped in one go, not in bits and pieces.
Includes fixing a typo in the ID for one of these fields.
* _N/A_ Functionally, there should be no noticeable difference

QA: fix incorrect attribute escapes

---

js/src/yoastseo-woo-identifiers.js

* The existing code was fragile and did not cover many edge cases (e.g. updating the data on (bulk) removal of variations). This PR refactors it and solves some bugs related to these edge cases.
* Fixes a bug where an empty SKU was not picked up in the SKU assessment.
* Fixes a bug where changes to the SKU and product identifiers were not picked up in the SKU and product identifier assessments when performing bulk actions, like bulk delete, bulk price increase and bulk price decrease.
* Fixes a bug where entering a price before entering an SKU lead to incorrect SKU assessment results.
* Code has been refactored quite a bit:
* SKU and product identifier data is gathered from the page when the analysis is run. This simplifies the …

Refactors code that sends over SKU and product identifier data to the analysis

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Sets the minimum required version to the latest RC.
*
* Test the 15.2 Woo release zip with a Yoast SEO Free zip version less than 19.6
* You should get an error where you are required to update your Yoast SEO Free version
* Replace the Yoast SEO zip with the version created from the 19.6 release branch
* Confirm that the error does not appear anymore
*
*
Fixes #

Set the minimum required version to the latest RC

---

classes/woocommerce-schema.php
classes/woocommerce-seo.php
classes/woocommerce-yoast-ids.php
classes/woocommerce-yoast-tab.php
js/src/yoastseo-woo-replacevars.js
tests/classes/schema-test.php

* Schema.org in the process of adding support for ASIN values (Amazon Standard Identification Number) on Product/Offer nodes.
* Enhances the global identifiers feature for Products and variations to include the ASIN product ID and add it to the Schema output.
* These are not included in the product identifier assessment by design.
* Enable the latest stable version of free and premium.
* Add a new product. And give it a name and a price.
* Add an ASIN in the Yoast SEO tab in the woocommerce meta box.
* See that the product identifier assessment still says ` Your product is missing a product identifier (like a GTIN code).`
* Add a GTIN option in the same Yoast SEO tab as …

Add support for ASIN product identifier.

---

js/src/yoastseo-woo-identifiers.js

* The SKU and product identifiers assessment result wasn't updating without refreshing the page when performing a bulk action on variants, or when deleting a variant.
* Fixes an unreleased bug where the SKU and product identifier assessment results weren't updating without refreshing the page when performing a bulk action on product variants, or when deleting a variant.
* Observing the whole variations tab, with the `subtree`, `attributes`, and `childList` options, ensures that all the changes to variant data are detected.
* Activate Yoast SEO Free, WooCommerce, and Yoast SEO: WooCommerce plugins
* (for acceptance tester) Make sure to run `composer require …

Fix the assessment results for SKU and product identifier not always updating for variable products

---

js/src/yoastseo-woo-identifiers.js

*
* Fixes an unreleased bug where the SKU and product identifiers assessment results would not update when opening a saved product with variants and deleting the variants.
* The bug was caused by the fact that if no variation elements are found, we get the variant data from the JavaScript object injected by the server. Since the variation elements are not immediately available on page load, this ensures that we still can retrieve the variants on page load. However, when we remove the variants after opening the page, the variation elements are also not found (because they were removed), but the data from the JS objected injected by the server is not updated without refreshing the page. So in that situation, we falsely think that …

Fix SKU assessment not updating when variants are deleted after opening a saved product

---

js/src/yoastseo-woo-identifiers.js

* This [PR](https://github.com/Yoast/wpseo-woocommerce/pull/823) resulted in a console error and the assessments not showing up on a new product without variants. This is because it introduced code that always tries to get the attribute of the element with the `woocommerce_variations` class, even when that element doesn't exist. This PR fixes it so that we only get the attribute if the element exists.
* Fixes an unreleased bug where the SKU and product identifier assessments did not show up on a new product without variants.
* If the element with the `woocommerce_variations` class doesn't exist, it means the product doesn't have variants, so we don't need to try to get the initial variant data.
This PR can be acceptance tested by …

Fix SKU and product identifier assessments not showing up on a new product without variants

---

js/src/yoastseo-woo-identifiers.js

*
* Adds information about whether the product identifiers can be retrieved to the custom data. Sets the identifier to an empty string if it cannot be retrieved.
* When retrieving the identifiers, if at least one of the identifier input fields cannot be retrieved, the `canRetrieveAllVariantIdentifiers` / `canRetrieveAllIdentifiers` variable is set to false. However, in the data that is sent to the paper, `canRetrieveGlobalIdentifier ` and `canRetrieveVariantIdentifiers` are only set to false when at least one identifier cannot be retrieved AND no other identifier field is filled in. This is because you only need to fill in one identifier to get a green bullet, so as long as one is filled in it doesn't matter if some other input …

Check whether product identifiers can be retrieved

---

js/src/initializers/product-assessor.js

* We want to pass config for the SKU assessment when it is initialized in Woo. The reason is that we want to show feedback strings that explain where to add the SKU only for Woo, not for Shopify, at least for the present moment.
* Initializes the SKU assessment by including a feedback string that tells the user where to add the SKU.
*
* This PR is tested alongside this one: https://github.com/Yoast/wordpress-seo/pull/18946 
*
*
Fixes #https://yoast.atlassian.net/browse/PC-552

edit feedback strings for SKU and PI assessment

---

classes/option-woo.php
classes/woocommerce-schema.php
classes/woocommerce-seo.php
tests/classes/schema-test.php

* Improve `Offers` / `priceSpecification` output to match Google's recent changes to their guidelines.
* Improves the Schema output for for `Offers` and `priceSpecification` to match Google's recent changes to their guidelines.
* Adds a feature to select a custom taxonomy for products to describe their `pattern` in the Schema output.
* Add some brands and manufacturers in Yoast SEO > WooCommerce SEO (the instructions are the same as per "Pattern" below)
* Create and publish some products (at least a simple one and a variable one)
* See that in the schema for `Product` > `offers` the `price` and `priceCurrency` properties have been moved inside `priceSpecification`
* See …

Improve Offers / priceSpecification output

---

js/src/yoastseo-woo-identifiers.js

* The Identifier assessment was only updated once the input field was 'un-focused' by clicking elsewhere on the page. This was not true for the SKU assessment.
* This PR fixes that by changing the type of event-listener.
* Fixes an unreleased bug where the Product identifier assessment was only updated once the identifier field was de-focussed.
* Also changed the event listener type for the sku input field. This worked before this PR. But I think it is better to keep the listeners to sku and identifier uniform. I added test instruction to also check sku.
* Create a simple product.
* Make sure that the SKU assessment gives the following feedback:
> SKU: Your product is …

PC-613-product-identifier-feedback-only-updates-when-you-click-on-the-page

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* We want to avoid the GSC tool to display a "Duplicate field" warning when `pattern` or `color` are set to an array of multiple element.
* Fixes a bug where the Product Schema output would trigger a "Duplicate field" warning for the `color` property for non-variable products.
* the changelog lines mentions only the `color` property because the `pattern` one is being introduced in this version.
* Create two attributes, one for color and the other for pattern
* add some terms to both
* in the WooCommerce SEO settings, set the attributes to color and pattern
* Create a new product (either Simple, Grouped or External)
* under Attributes, add the attributes you just created
* …

PC-626 Fix the `color` and `pattern` output

---

classes/option-woo.php
classes/woocommerce-schema.php
classes/woocommerce-seo.php
tests/classes/schema-test.php

*
* Adds a `material` property to products' pages schema.
*
* Activate Yoast SEO and Yoast SEO for WooCommerce.
* Go to the administration dashboard and click on Yoast SEO -> WooCommerce SEO.
* Set the `Material` option to `Product categories`.
* Click on `Products` -> `Add new`.
* Set a name and price for the product. Also add a category.
* Go to the product page, inspect the source code and scroll down to the product schema data.
* Observe that in the Product type a `material` item exists which is set to the product category.
*
*
Fixes …

Add material to schema data output

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* For the PR on Yoast SEO, we changed the `@id` of the `image`s in the schema to the URL of the image instead of the `#primaryimage` identifier. This PR fixes the change in ID for WooCommerce products.
* Note that this PR should be released together with [this PR](https://github.com/Yoast/wordpress-seo/pull/18916) in Yoast SEO.
* Adjust the `@id` property of `image`s in the schema data to the URL of the image instead of the `#primaryimage` identifier.
*
* Activate both Yoast SEO and Yoast SEO for WooCommerce.
* Create a product and *do not* add an image just yet.
* Check the page source of the product and see whether schema for the `Product` type *does not* have an …

Change image id from hash to image url

---

classes/woocommerce-seo.php

* We want to declare compatibility with High Performance Order Storage feature in WooCommerce 7.1+. Yoast SEO doesn't perform any operation on WC orders, so it's not affected by the switch to custom tables.
* Ensures compatibility with the High Performance Order Storage feature in WooCommerce 7.1+.
*
* Install the WooCommerce zip from the [HPOS feature release page](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table) and install it.
* make sure you have  Free with [this branch](https://github.com/Yoast/wordpress-seo/pull/19085) active
* checkout this branch and activate
* create one or more orders under WooCommerce > Orders
* visit …

PC-868 Declare compatibility with the HPOS feature (WooCommerce 7.1+)

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

* Bumps the Yoast SEO minimum required version to 19.10.
* Bumps the Yoast SEO minimum required version to 19.10.
*
* NA
*
*
Fixes #

Bumps the Yoast SEO minimum required version to 19.10.

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/integrationtest.yml
.github/workflows/lint.yml
.github/workflows/unittest.yml

* CI maintenance
* CI maintenance
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Caches used in GH Actions …

Gh Actions: various tweaks

---

tests/classes/slack-test.php
tests/classes/twitter-test.php
tests/classes/woocommerce-yoast-ids-test.php

* Improve compatibility with PHP 8.2
* Improve compatibility with PHP 8.2
This is a test only change.
Mockery is used to create some anonymous mocks/mocks for unavailable classes and then either the tests or the code under test sets properties on those mock objects, which leads to "Creation of dynamic property ... is deprecated" notices on PHP 8.2.
To fix this, I'm proposing the following:
1. For the mock for an unavailable class - `WP_Post` in `WooCommerce_Yoast_Ids_Test` - let the mock `extend` `stdClass` to allow properties to be set. As the method under test does not have a type declaration for the expected parameter, this will not run into a `TypeError` and extending `stdClass` allows for setting dynamic properties on the …

PHP 8.2 | Tests: fix some dynamic property creation errors in the tests

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Sets the minimum required Yoast SEO version to 19.12.
*
*
*
*
Fixes #

bump the required free version to 19.12

---

.github/workflows/integrationtest.yml
README.md
classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

* Sets the minimum supported WordPress version to 6.0.
* Sets the minimum supported WordPress version to 6.0.
*
*
*
*
Fixes #

Set minimum WP version to 6.0

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

*
* Improves the Schema output for `Product`, including a fix for a bug affecting setups where prices are inserted without taxes but displayed with taxes or viceversa.
* I've just adapted the existing unit tests but they fail short from covering the wide array of cases we'd need to check. Integration tests would definitely be a better choice.
* create a simple Product with price set to 10.00
* create a variable product with three variations, with prices set to 8.00, 11.00, 12.00
- in the WooCommerce settings, untick "Enable tax rates and calculations" and save.
- visit the Simple product
- Check the schema for the `Product` piece, look at the `offers` property:
``` …
```

Fix the Schema for Product prices with and without taxes

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
*  Sets the minimum required version of Yoast SEO to 19.14.
*
*
*
*
Fixes #

Bump minimum Free version to 19.14

---

classes/woocommerce-schema.php
tests/classes/schema-test.php

* Because
* we no longer create indexables for attachments
* we instead use the SEO Link table for retrieving an image's id 
* and the placeholder image will almost never gonna be in the SEO_Links table
* we now don't use the SEO link table for products with only a placeholder image, so that we avoid performing an unnecessary query 
* Make product schema creation compatible with the latest Yoast Free changes
* 
* No test instructions, since we're just refactoring some code to follow the new way of attachment indexable handling.
* Follow the impact check, to understand what to test
*
This PR affects the following parts of the …

Never use the link table when looking for the placeholder image in Woo products

---

classes/woocommerce-seo.php

* Fixes link to Breadcrumbs settings on WooCommerce SEO v15.4 add-on
* Improves the Breadcrumb settings' link to point to a more specific section in the new Yoast settings.
*
* Install WooCommerce SEO v15.4 add-on
* Go to `YoastSEO`->`Woocommerce SEO`
* Click on the link `Breadcrub setting page`
* Check you are redirected to `wp-admin/admin.php?page=wpseo_page_settings#/breadcrumbs`
*
*
Fixes https://github.com/Yoast/plugins-automated-testing/issues/339
https://github.com/Yoast/wordpress-seo/issues/19422

fix breadcrumb link

---

js/src/initializers/product-assessor.js

*
* Removes the shortlinks of _keyphrase distribution_ and _word complexity_ assessments from the product assessor initializer. 
* This is a complementary task to the PR that removes [Premium assessments from productPages assessors](https://github.com/Yoast/wordpress-seo/pull/19897#top)
* This task should be tested together with task to [Remove Premium assessments from productPages assessors](https://github.com/Yoast/wordpress-seo/pull/19897#top). 
*
* N/a
Fixes #[19828](https://github.com/Yoast/wordpress-seo/issues/19828)

Remove keyphraseDistribution and wordComplexity from the product assessor initializer

---

.github/workflows/deploy.yml
.github/workflows/integrationtest.yml
.github/workflows/lint.yml
.github/workflows/unittest.yml
README.md
composer.json
composer.lock
languages/yoast-woo-seo.pot
wpseo-woocommerce.php

This PR depends on https://github.com/Yoast/wordpress-seo/pull/19948.
After that one has been merged, we need to update this so it points to  Free `trunk` (`composer require yoast/wordpress-seo:dev-trunk@dev --dev`) and check that GH action still pass.
*
* Drops compatibility with PHP 5.6, 7.0 and 7.1.
*
* Verify the GH actions pass
* install on a PHP 5.6 environment
* visit the Plugins page
* see that you get the same message and you can't activate the plugin, as it happens here for Free and Premium:
* the same should happen with 7.0 and 7.1
**note**: the above may be tricky to test. I can see 5.6 as a choice in Local by Flywheel, but I know it's not the case for others …

Drop compatibility with PHP 5.6, 7.0 and 7.1

---

classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Bumps the minimum required version of Yoast SEO to 20.6.
*
*
*
*
Fixes #

Bump minimum required version to 20.6 (again)

---

js/src/yoastseo-woo-replacevars.js

* This PR prevents an error when the short description metabox is not present. We do so by adding some defensive coding in fetching the short description.
* Fixes a bug where the Yoast SEO metabox would not load when the short description metabox had been deactivated.
* Did not boy scout the rest of the file to keep the impact as minimal as possible.
* First, reproduce the original bug using the instructions in #897, including updating your `functions.php` file. 
* Then, with this PR, note that the Yoast metabox still works and the console error is no longer shown.
* Also, confirm that you can add the replacement variable `wc_shortdesc` to the SEO title / meta …

Prevents an error when the short description metabox is not present

---

.github/workflows/integrationtest.yml
README.md
classes/woocommerce-dependencies.php
tests/classes/woocommerce-dependencies-test.php

*
* Sets the minimum supported WordPress version to 6.1.
*
* N/A
* N/A
*
Fixes #

Set the minimum supported WordPress version to 6.1

---

.github/workflows/test.yml
.gitignore
README.md
composer.json
phpunit-integration.xml.dist
phpunit.xml.dist

* Enable test code coverage monitoring.
* Enable test code coverage monitoring.
This commit makes the necessary changes to start recording and uploading code coverage data to Coveralls.
Includes:
* Updating the GH Actions `test` workflow to run the high/low PHP version builds with code coverage and upload the results.
* Updating the PHPUnit config to record coverage and show an inline code coverage summary.
* Ignoring the potentially generated code coverage files in the `build/*` directory to prevent it being committed.
* Adding scripts to the `composer.json` file to run code coverage.
* Adding a code coverage badge to the README.
Notes:
* Coverage will be recorded using `Xdebug` as the code coverage driver.
* Recording code …

CI/QA: start recording code coverage

---

.github/workflows/test.yml

* CI maintenance
* CI maintenance
This syncs the logic for determining the MySQL version to use in the integration tests with the logic used by the majority of plugins.
The difference is historic as the original script was based on what was being done in Travis, which was not always the same between plugins.
This commit is part of a standardization round.
* _N/A_ If the tests run & pass, we're good.

GH Actions/integration test: test against MySQL 5.6

---

.github/workflows/cs.yml
.github/workflows/js.yml
.github/workflows/lint.yml
.github/workflows/test.yml

* CI maintenance
* CI maintenance
Only run the workflows when there is a chance that the result of the workflow run will be different from before.
The path selection is set up to cast a wide net to make the risk of the workflows not running when the build could potentially break as small as possible.
This means that, aside from files of the type being checked in the workflow changing, the workflow will also run when:
* The configuration used changes.
* Dependencies used in the workflow may potentially have changed.
* Composer scripts used in the workflow may potentially have changed.
* Shell scripts used in the workflow have changed.
* The workflow itself changes.
* Miscellaneous related files have changed.
Note: the lists of …

GH Actions: run workflows more selectively

---

classes/woocommerce-seo.php

*
* Ensures compatibility of the breadcrumbs replacement feature with WooCommerce 7.9.0 when using blockified template for single products.
* Installing Woo 7.9.0 on a new site will enforce a single product _blockified_ template which is not compatible with the way we replace Woo breadcrumbs (i.e. replacing the function hooked into the `woocommerce_before_main_content` action) because it will rely on a block that we cannot hook into. It has been decided that we'll prevent any action in that case to avoid displaying 2 sets of breadcrumbs, which would not be matching.
* To detect if the single product is using a blockified template, we have to check that the template does not include `woocommerce/legacy-template`.
This PR can be …

Prevent replacing Woo breadcrumbs if using the blockified template

---

js/src/initializers/input-focus.js
js/tests/initializers/input-focus.test.js

* Actionable buttons for SKU and product identifier do not work in case variation product doesn't have variations.
* Fixes an unreleased bug where actionable buttons for _product identifier assessment_ and _SKU assessment_ would not work when a variable product did not have variations.
* Check if variable product has variations added. If no variations than it acts as for simple product.
Use the acceptance test plan for [the SKU assessment](https://docs.google.com/document/d/1pFWST3KtD3sT1WkKkz92AmoSycQrHht_g0-nQl39GrU/edit) and [the Product identifier assessment](https://docs.google.com/document/d/1kbBneoTf9CWYS2rRqzY5pZNK75Vb-os43nAd2Br80_w/edit).
Scenario 1: SKU …

870 fix actionable buttons for variation product without variations

---

.gitignore
classes/woocommerce-seo.php
classes/woocommerce-yoast-tab.php
tests/classes/woocommerce-yoast-tab-test.php

* Remove `filter_input` usage.
* Removes `filter_input` usage for PHP 8.1 improvements.
*
* Go to `Yoast SEO`->`Woocommerce SEO` 
* Check page looks as expected.
* Inspect page and search in `Elements` tab (or in page source) for `yoast-seo-admin-css-css`
* Check you find it once and a link to a style sheet.
* Go to `Products`, add a product or edit an existing product.
* Go to the woocommerce section in the product and go `Yoast SEO` tab
* Add values to the fields and save.
* Check fields were saved.
*
*
Fixes #918

918 woocommerce seo php 81 improvements

---

composer.json
composer.lock

* Tidy up `composer.json` file and improve usability of scripts
* Tidy up `composer.json` file and improve usability of scripts
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
These descriptions will be used when a list of the available scripts is requested on the command-line using the `composer list` or `composer run -l` commands.
These descriptions also help document the different scripts for the maintainers of the `composer.json` file.
Ref: …

Composer: normalize the file, add script descriptions

---

composer.json
composer.lock

* Users requiring this package via [WP]Packagist can now use the `composer/installers` v2.
* Users requiring this package via [WP]Packagist can now use the `composer/installers` v2.
While the latest version of the `composer/installers` package is `2.2`, I'm explicitly setting the version constraint to a lenient one as this is a non-`dev` requirement, which comes into play when people use a [WP]Packagist based site setup.
If we set the requirement very strictly, it could conflict with other plugins with different constraints and it is not as if any of the 2.x releases have touched the WordPress installer, so setting it to `|| 2.0` should be fine.
* _N/A_

Composer: allow composer installers 2.x

---

tests/Unit/Classes/Integrations/TranslationsPress_Test.php
tests/Unit/Classes/Yoast_Ids_Test.php
tests/Unit/Classes/Yoast_Tab_Test.php
tests/WP/Classes/Option_Woo_Test.php

*
* Tests: use static dataproviders
As of PHPUnit 10, data providers are (again) expected to be `static` methods.
This updates the test suite to respect that.
* _N/A_ If the builds pass, we're good.

Tests: make dataproviders `static`

---

classes/woocommerce-import-export.php
tests/Unit/Classes/Import_Export_Test.php

* We want to support variations in our global identifier import/export tool.
* Extends the global identifier import/export feature to variations.
* N/A
* Instructions in #945 have been updated to take into account variations, please refer to them.
* N/A
Fixes #

Extend the global identifier import/export feature to variations

---

classes/woocommerce-opengraph.php

* We want to avoid showing a Php 8.0 warning when trying to access a property of a non-object.
* Avoids triggering a PHP 8 warning when attempting to access a non-existent object. Props to @37Rb.
* N/A
* Make sure your site is running on Php version 8.0 or higher 
* Make sure you have at least one product published
* Either use the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin or add the following filter to your theme's `functions.php`:
```
add_filter( 'wpseo_indexable_excluded_post_types', function( $post_types ) {
$post_types[] = 'product';
return $post_types;
} );
```
* Reset your indexables table through the `Yoast Test Helper`
* Without this PR:
*  you get a Php Warning: Attempt to read property …

Fix #875 attempt to read undefined property warning
